\n\n-- Drop existing triggers if they exist (cleanup)\nDROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
\nDROP TRIGGER IF EXISTS on_new_user_referral_credit ON auth.users;
\n\n-- Drop existing functions if they exist (cleanup)\nDROP FUNCTION IF EXISTS public.create_user_profile();
\nDROP FUNCTION IF EXISTS public.assign_referral_code(UUID);
\nDROP FUNCTION IF EXISTS public.credit_referral_signup_bonus();
\n\n-- 1. Create the user profile creation function\nCREATE OR REPLACE FUNCTION public.create_user_profile()\nRETURNS TRIGGER AS $$\nBEGIN\n  INSERT INTO public.user_profiles (\n    id,\n    full_name,\n    email_address,\n    is_active,\n    profile_created_at,\n    profile_updated_at,\n    referred_by\n  )\n  VALUES (\n    NEW.id,\n    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1), 'User'),\n    NEW.email,\n    true,\n    now(),\n    now(),\n    COALESCE(NEW.raw_user_meta_data->>'referralCode', NULL)\n  )\n  ON CONFLICT (id) DO UPDATE SET\n    full_name = COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1), user_profiles.full_name),\n    email_address = NEW.email,\n    profile_updated_at = now(),\n    referred_by = COALESCE(NEW.raw_user_meta_data->>'referralCode', user_profiles.referred_by);
\n  \n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- 2. Create the referral code assignment function\nCREATE OR REPLACE FUNCTION public.assign_referral_code(user_uuid UUID)\nRETURNS TEXT AS $$\nDECLARE\n  generated_code TEXT;
\n  existing_code TEXT;
\n  max_attempts INTEGER := 10;
\n  attempt_count INTEGER := 0;
\nBEGIN\n  -- Check if a referral code already exists for the user\n  SELECT referral_code INTO existing_code \n  FROM public.user_profiles \n  WHERE id = user_uuid;
\n\n  IF existing_code IS NOT NULL THEN\n    RETURN existing_code;
\n  END IF;
\n\n  -- Generate a unique 8-character alphanumeric code\n  LOOP\n    generated_code := upper(substring(md5(random()::text || clock_timestamp()::text) for 8));
\n    \n    -- Check if this code already exists\n    IF NOT EXISTS (SELECT 1 FROM public.user_profiles WHERE referral_code = generated_code) THEN\n      EXIT;
 -- Code is unique, exit loop\n    END IF;
\n    \n    attempt_count := attempt_count + 1;
\n    IF attempt_count >= max_attempts THEN\n      RAISE EXCEPTION 'Failed to generate unique referral code after % attempts', max_attempts;
\n    END IF;
\n  END LOOP;
\n\n  -- Update the user's profile with the new referral code\n  UPDATE public.user_profiles\n  SET \n    referral_code = generated_code, \n    profile_updated_at = now()\n  WHERE id = user_uuid;
\n\n  -- Verify the update was successful\n  IF NOT FOUND THEN\n    RAISE EXCEPTION 'User profile not found for UUID: %', user_uuid;
\n  END IF;
\n\n  RETURN generated_code;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- 3. Create the referral signup bonus function\nCREATE OR REPLACE FUNCTION public.credit_referral_signup_bonus()\nRETURNS TRIGGER AS $$\nDECLARE\n  referrer_profile_id UUID;
\n  referred_by_code TEXT;
\n  signup_bonus_amount NUMERIC := 10.00;
 -- ₹10 signup bonus\n  new_user_bonus_amount NUMERIC := 10.00;
 -- ₹10 bonus for new user\nBEGIN\n  -- Extract referral code from user metadata\n  referred_by_code := NEW.raw_user_meta_data->>'referralCode';
\n\n  -- Only process if a referral code was provided\n  IF referred_by_code IS NOT NULL AND trim(referred_by_code) != '' THEN\n    \n    -- Find the referrer's profile ID using their referral code\n    SELECT id INTO referrer_profile_id\n    FROM public.user_profiles\n    WHERE referral_code = trim(referred_by_code);
\n\n    IF referrer_profile_id IS NOT NULL THEN\n      \n      -- Prevent self-referral\n      IF referrer_profile_id = NEW.id THEN\n        RAISE WARNING 'User % attempted self-referral with code %', NEW.id, referred_by_code;
\n        RETURN NEW;
\n      END IF;
\n\n      -- Check if this specific referral bonus has already been credited\n      IF NOT EXISTS (\n        SELECT 1 FROM public.wallet_transactions\n        WHERE user_id = NEW.id\n        AND type = 'referral_signup_bonus'\n        AND source_user_id = referrer_profile_id\n      ) THEN\n        \n        -- Credit bonus to the new user (referred user)\n        INSERT INTO public.wallet_transactions (\n          user_id, \n          type, \n          amount, \n          status, \n          source_user_id, \n          transaction_ref,\n          redeem_details\n        )\n        VALUES (\n          NEW.id, \n          'referral_signup_bonus', \n          new_user_bonus_amount, \n          'completed', \n          referrer_profile_id, \n          'signup_bonus_new_user_' || NEW.id,\n          jsonb_build_object(\n            'bonus_type', 'new_user_signup',\n            'referral_code_used', referred_by_code,\n            'referrer_id', referrer_profile_id\n          )\n        );
\n\n        -- Credit bonus to the referrer\n        INSERT INTO public.wallet_transactions (\n          user_id, \n          type, \n          amount, \n          status, \n          source_user_id, \n          transaction_ref,\n          redeem_details\n        )\n        VALUES (\n          referrer_profile_id, \n          'referral_signup_bonus', \n          signup_bonus_amount, \n          'completed', \n          NEW.id, \n          'signup_bonus_referrer_' || NEW.id,\n          jsonb_build_object(\n            'bonus_type', 'referrer_signup',\n            'referred_user_id', NEW.id,\n            'referral_code', referred_by_code\n          )\n        );
\n\n        RAISE NOTICE 'Referral signup bonus credited: ₹% to new user % and ₹% to referrer %', \n          new_user_bonus_amount, NEW.id, signup_bonus_amount, referrer_profile_id;
\n      ELSE\n        RAISE NOTICE 'Referral signup bonus already credited for new user %', NEW.id;
\n      END IF;
\n    ELSE\n      RAISE WARNING 'Referral code % not found for new user %', referred_by_code, NEW.id;
\n    END IF;
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- 4. Create trigger for user profile creation\nCREATE TRIGGER on_auth_user_created\n  AFTER INSERT ON auth.users\n  FOR EACH ROW EXECUTE FUNCTION public.create_user_profile();
\n\n-- 5. Create trigger for referral signup bonus\nCREATE TRIGGER on_new_user_referral_credit\n  AFTER INSERT ON auth.users\n  FOR EACH ROW EXECUTE FUNCTION public.credit_referral_signup_bonus();
\n\n-- 6. Ensure referred_by column is nullable (if it isn't already)\nDO $$\nBEGIN\n  -- Check if referred_by column exists and make it nullable if needed\n  IF EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' \n    AND column_name = 'referred_by'\n    AND table_schema = 'public'\n  ) THEN\n    -- Make sure the column is nullable\n    ALTER TABLE public.user_profiles ALTER COLUMN referred_by DROP NOT NULL;
\n    RAISE NOTICE 'referred_by column made nullable';
\n  END IF;
\nEND $$;
\n\n-- 7. Ensure source_user_id column exists in wallet_transactions and is nullable\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'wallet_transactions' \n    AND column_name = 'source_user_id'\n    AND table_schema = 'public'\n  ) THEN\n    ALTER TABLE public.wallet_transactions ADD COLUMN source_user_id UUID REFERENCES public.user_profiles(id) ON DELETE SET NULL;
\n    RAISE NOTICE 'source_user_id column added to wallet_transactions';
\n  END IF;
\nEND $$;
\n\n-- 8. Create index for better performance on referral code lookups\nCREATE INDEX IF NOT EXISTS idx_user_profiles_referral_code_lookup \nON public.user_profiles(referral_code) \nWHERE referral_code IS NOT NULL;
\n\n-- 9. Create index for wallet transactions referral lookups\nCREATE INDEX IF NOT EXISTS idx_wallet_transactions_referral_bonus \nON public.wallet_transactions(user_id, type, source_user_id) \nWHERE type = 'referral_signup_bonus';
\n\n-- 10. Grant necessary permissions\nGRANT EXECUTE ON FUNCTION public.create_user_profile() TO authenticated, anon;
\nGRANT EXECUTE ON FUNCTION public.assign_referral_code(UUID) TO authenticated, service_role;
\nGRANT EXECUTE ON FUNCTION public.credit_referral_signup_bonus() TO authenticated, anon;
\n\n-- Log completion\nDO $$\nBEGIN\n  RAISE NOTICE 'Signup and referral system restoration completed successfully';
\n  RAISE NOTICE 'Functions created: create_user_profile, assign_referral_code, credit_referral_signup_bonus';
\n  RAISE NOTICE 'Triggers created: on_auth_user_created, on_new_user_referral_credit';
\n  RAISE NOTICE 'Signup bonus amount set to: ₹10.00 for both new users and referrers';
\nEND $$;
;
