/*\n  # Add Interview Session Backups Table\n  \n  1. New Tables\n    - `interview_session_backups`\n      - `id` (uuid, primary key) - Unique identifier\n      - `session_id` (text, unique) - Reference to the interview session\n      - `user_id` (uuid) - Reference to the user\n      - `current_question_index` (integer) - Current question being answered\n      - `total_questions` (integer) - Total number of questions\n      - `time_remaining` (integer) - Remaining time in seconds\n      - `current_transcript` (text) - Current speech transcript\n      - `text_answer` (text) - Current text answer\n      - `code_answer` (text) - Current code answer\n      - `selected_language` (text) - Selected programming language\n      - `questions_answered` (integer) - Number of questions answered\n      - `questions_skipped` (integer) - Number of questions skipped\n      - `interview_type` (text) - Type of interview (realistic, smart, adaptive)\n      - `last_saved` (timestamptz) - Last save timestamp\n      - `created_at` (timestamptz) - Creation timestamp\n      - `updated_at` (timestamptz) - Last update timestamp\n      \n  2. Security\n    - Enable RLS on `interview_session_backups` table\n    - Add policies for users to manage their own session backups\n*/\n\nCREATE TABLE IF NOT EXISTS interview_session_backups (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  session_id text UNIQUE NOT NULL,\n  user_id uuid NOT NULL,\n  current_question_index integer DEFAULT 0,\n  total_questions integer DEFAULT 0,\n  time_remaining integer DEFAULT 0,\n  current_transcript text DEFAULT '',\n  text_answer text DEFAULT '',\n  code_answer text DEFAULT '',\n  selected_language text DEFAULT 'Python',\n  questions_answered integer DEFAULT 0,\n  questions_skipped integer DEFAULT 0,\n  interview_type text NOT NULL CHECK (interview_type IN ('realistic', 'smart', 'adaptive')),\n  last_saved timestamptz DEFAULT now(),\n  created_at timestamptz DEFAULT now(),\n  updated_at timestamptz DEFAULT now()\n);
\n\nALTER TABLE interview_session_backups ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Users can view own session backups"\n  ON interview_session_backups\n  FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can create own session backups"\n  ON interview_session_backups\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own session backups"\n  ON interview_session_backups\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can delete own session backups"\n  ON interview_session_backups\n  FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE INDEX IF NOT EXISTS idx_session_backups_user_type \n  ON interview_session_backups(user_id, interview_type, last_saved DESC);
\n\nCREATE INDEX IF NOT EXISTS idx_session_backups_session_id \n  ON interview_session_backups(session_id);
\n;
