\n\n-- Create the new user_profiles table\nCREATE TABLE user_profiles (\n  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,\n  full_name text NOT NULL,\n  email_address text NOT NULL,\n  is_active boolean DEFAULT true NOT NULL,\n  profile_created_at timestamptz DEFAULT now() NOT NULL,\n  profile_updated_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Enable Row Level Security\nALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
\n\n-- Create security policies\nCREATE POLICY "Users can view own profile"\n  ON user_profiles\n  FOR SELECT\n  TO authenticated\n  USING (auth.uid() = id);
\n\nCREATE POLICY "Users can create own profile"\n  ON user_profiles\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = id);
\n\nCREATE POLICY "Users can modify own profile"\n  ON user_profiles\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id)\n  WITH CHECK (auth.uid() = id);
\n\n-- Function to automatically update the timestamp\nCREATE OR REPLACE FUNCTION update_profile_timestamp()\nRETURNS TRIGGER AS $$\nBEGIN\n  NEW.profile_updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ language 'plpgsql';
\n\n-- Trigger for automatic timestamp updates\nCREATE TRIGGER update_user_profiles_timestamp\n  BEFORE UPDATE ON user_profiles\n  FOR EACH ROW\n  EXECUTE FUNCTION update_profile_timestamp();
\n\n-- Function to create profile when user signs up\nCREATE OR REPLACE FUNCTION create_user_profile()\nRETURNS TRIGGER AS $$\nBEGIN\n  INSERT INTO public.user_profiles (\n    id, \n    full_name, \n    email_address, \n    is_active,\n    profile_created_at, \n    profile_updated_at\n  )\n  VALUES (\n    NEW.id,\n    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1), 'User'),\n    NEW.email,\n    true,\n    now(),\n    now()\n  )\n  ON CONFLICT (id) DO UPDATE SET\n    full_name = COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1), user_profiles.full_name),\n    email_address = NEW.email,\n    profile_updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Trigger to automatically create profile on user signup\nCREATE TRIGGER create_profile_on_signup\n  AFTER INSERT ON auth.users\n  FOR EACH ROW EXECUTE FUNCTION create_user_profile();
\n\n-- Create performance indexes\nCREATE INDEX user_profiles_id_index ON user_profiles(id);
\nCREATE INDEX user_profiles_email_index ON user_profiles(email_address);
\nCREATE INDEX user_profiles_created_index ON user_profiles(profile_created_at);
\nCREATE INDEX user_profiles_active_index ON user_profiles(is_active);
;
