\n\n-- Create wallet_transactions table\nCREATE TABLE IF NOT EXISTS public.wallet_transactions (\n    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n    user_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,\n    source_user_id uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,\n    type text NOT NULL CHECK (type IN ('referral', 'redeem', 'purchase_use', 'adjustment', 'referral_signup_bonus')),\n    amount numeric(10, 2) NOT NULL,\n    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'processing', 'failed')),\n    redeem_method text CHECK (redeem_method IN ('upi', 'bank_transfer')),\n    redeem_details jsonb,\n    transaction_ref text,\n    created_at timestamp with time zone NOT NULL DEFAULT now(),\n    updated_at timestamp with time zone NOT NULL DEFAULT now()\n);
\n\n-- Enable Row Level Security\nALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;
\n\n-- RLS Policy: Users can view their own wallet transactions\nCREATE POLICY "Users can view their own wallet transactions" ON public.wallet_transactions\nFOR SELECT USING (user_id IN (\n    SELECT id FROM public.user_profiles WHERE user_id = auth.uid()\n));
\n\n-- RLS Policy: Users can insert their own transactions (redemptions)\nCREATE POLICY "Users can insert their own transactions" ON public.wallet_transactions\nFOR INSERT WITH CHECK (user_id IN (\n    SELECT id FROM public.user_profiles WHERE user_id = auth.uid()\n) AND type IN ('redeem', 'purchase_use'));
\n\n-- RLS Policy: System can insert any transaction (for referral bonuses)\nCREATE POLICY "System can insert transactions" ON public.wallet_transactions\nFOR INSERT WITH CHECK (true);
\n\n-- Create indexes for performance\nCREATE INDEX IF NOT EXISTS idx_wallet_transactions_user_id ON public.wallet_transactions (user_id);
\nCREATE INDEX IF NOT EXISTS idx_wallet_transactions_status ON public.wallet_transactions (status);
\nCREATE INDEX IF NOT EXISTS idx_wallet_transactions_type ON public.wallet_transactions (type);
\nCREATE INDEX IF NOT EXISTS idx_wallet_transactions_created_at ON public.wallet_transactions (created_at);
\n\n-- Function to update updated_at timestamp\nCREATE OR REPLACE FUNCTION public.update_wallet_updated_at()\nRETURNS TRIGGER AS $$\nBEGIN\n    NEW.updated_at = now();
\n    RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql;
\n\n-- Trigger to update updated_at on wallet_transactions\nCREATE TRIGGER update_wallet_transactions_updated_at\n    BEFORE UPDATE ON public.wallet_transactions\n    FOR EACH ROW EXECUTE FUNCTION public.update_wallet_updated_at();
\n\n-- Function to credit referral signup bonus\nCREATE OR REPLACE FUNCTION public.credit_referral_signup_bonus()\nRETURNS TRIGGER AS $$\nDECLARE\n    _referral_code TEXT;
\n    _referrer_user_profile_id UUID;
\n    _new_user_profile_id UUID;
\nBEGIN\n    -- Get the referral code from the new user's raw_user_meta_data\n    _referral_code := NEW.raw_user_meta_data->>'referralCode';
\n\n    -- Get the user_profile ID for the new user\n    SELECT id INTO _new_user_profile_id \n    FROM public.user_profiles \n    WHERE user_id = NEW.id;
\n\n    -- Only proceed if we have a referral code and user profile\n    IF _referral_code IS NOT NULL AND _referral_code != '' AND _new_user_profile_id IS NOT NULL THEN\n        -- Find the referrer's user_profile ID based on the referral code (username)\n        SELECT id INTO _referrer_user_profile_id \n        FROM public.user_profiles \n        WHERE username = _referral_code AND is_active = true;
\n\n        -- If referrer found, credit the signup bonus\n        IF _referrer_user_profile_id IS NOT NULL THEN\n            INSERT INTO public.wallet_transactions (\n                user_id, \n                type, \n                amount, \n                status, \n                source_user_id,\n                transaction_ref\n            )\n            VALUES (\n                _new_user_profile_id, \n                'referral_signup_bonus', \n                10.00, \n                'completed', \n                _referrer_user_profile_id,\n                'signup_bonus_' || NEW.id\n            );
\n        END IF;
\n    END IF;
\n\n    RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Trigger to automatically credit referral signup bonus\nCREATE TRIGGER on_new_user_referral_credit\n    AFTER INSERT ON auth.users\n    FOR EACH ROW EXECUTE FUNCTION public.credit_referral_signup_bonus();
;
