/*\n  # Job Notification System\n\n  ## Overview\n  This migration creates the complete job notification system for daily digest emails\n  and welcome emails when users sign up.\n\n  ## Tables Created\n\n  1. **job_notification_subscriptions**\n     - Stores user subscription preferences for job alerts\n     - Fields: user_id, is_subscribed, preferred_domains, notification_frequency, last_sent_at\n     - Users can subscribe/unsubscribe and select their preferred job domains\n\n  2. **job_notification_logs**\n     - Tracks which jobs have been sent to which users to prevent duplicates\n     - Fields: user_id, job_id, sent_at, email_status\n     - Ensures users don't receive the same job multiple times\n\n  3. **email_logs**\n     - Comprehensive email delivery tracking for all email types\n     - Fields: user_id, email_type, recipient_email, status, sent_at, error_message\n     - Tracks welcome emails, job digests, and delivery status\n\n  ## Security (RLS Policies)\n  \n  - Users can view and update their own notification subscriptions\n  - Users can view their own notification logs\n  - Admins can view all subscriptions and logs for analytics\n  - Email logs are restricted to authenticated users for their own records\n\n  ## Indexes\n  \n  - Optimized for querying subscriptions by user_id and subscription status\n  - Indexed preferred_domains for fast domain-based filtering\n  - Indexed notification_logs by job_id and sent_at for duplicate prevention\n  - Email logs indexed by user_id and email_type for quick lookups\n\n  ## Helper Functions\n  \n  - get_subscribed_users_for_domain(): Returns users subscribed to specific domain\n  - check_if_job_sent_to_user(): Prevents duplicate job notifications\n  - log_notification_send(): Records notification delivery\n  - get_notification_statistics(): Admin analytics for notification metrics\n*/\n\n-- ============================================================================\n-- JOB NOTIFICATION SUBSCRIPTIONS\n-- ============================================================================\n\nCREATE TABLE IF NOT EXISTS job_notification_subscriptions (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n  is_subscribed boolean DEFAULT true NOT NULL,\n  preferred_domains text[] DEFAULT ARRAY[]::text[] NOT NULL,\n  notification_frequency text DEFAULT 'daily' NOT NULL CHECK (notification_frequency IN ('daily', 'immediate', 'weekly')),\n  last_sent_at timestamptz,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  updated_at timestamptz DEFAULT now() NOT NULL,\n  UNIQUE(user_id)\n);
\n\nALTER TABLE job_notification_subscriptions ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Users can view own subscription"\n  ON job_notification_subscriptions FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can insert own subscription"\n  ON job_notification_subscriptions FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own subscription"\n  ON job_notification_subscriptions FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can delete own subscription"\n  ON job_notification_subscriptions FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Admins can view all subscriptions"\n  ON job_notification_subscriptions FOR SELECT\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\nCREATE INDEX IF NOT EXISTS idx_notification_subs_user ON job_notification_subscriptions(user_id);
\nCREATE INDEX IF NOT EXISTS idx_notification_subs_active ON job_notification_subscriptions(is_subscribed) WHERE is_subscribed = true;
\nCREATE INDEX IF NOT EXISTS idx_notification_subs_domains ON job_notification_subscriptions USING GIN (preferred_domains);
\nCREATE INDEX IF NOT EXISTS idx_notification_subs_last_sent ON job_notification_subscriptions(last_sent_at);
\n\n-- ============================================================================\n-- JOB NOTIFICATION LOGS\n-- ============================================================================\n\nCREATE TABLE IF NOT EXISTS job_notification_logs (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n  job_id uuid NOT NULL REFERENCES job_listings(id) ON DELETE CASCADE,\n  sent_at timestamptz DEFAULT now() NOT NULL,\n  email_status text DEFAULT 'sent' NOT NULL CHECK (email_status IN ('sent', 'failed', 'pending')),\n  notification_type text DEFAULT 'daily_digest' NOT NULL CHECK (notification_type IN ('daily_digest', 'immediate', 'manual')),\n  created_at timestamptz DEFAULT now() NOT NULL\n);
\n\nALTER TABLE job_notification_logs ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Users can view own notification logs"\n  ON job_notification_logs FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "System can insert notification logs"\n  ON job_notification_logs FOR INSERT\n  TO authenticated\n  WITH CHECK (true);
\n\nCREATE POLICY "Admins can view all notification logs"\n  ON job_notification_logs FOR SELECT\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\nCREATE INDEX IF NOT EXISTS idx_notification_logs_user ON job_notification_logs(user_id);
\nCREATE INDEX IF NOT EXISTS idx_notification_logs_job ON job_notification_logs(job_id);
\nCREATE INDEX IF NOT EXISTS idx_notification_logs_sent_at ON job_notification_logs(sent_at DESC);
\nCREATE INDEX IF NOT EXISTS idx_notification_logs_user_job ON job_notification_logs(user_id, job_id);
\n\n-- ============================================================================\n-- EMAIL LOGS\n-- ============================================================================\n\nCREATE TABLE IF NOT EXISTS email_logs (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,\n  email_type text NOT NULL CHECK (email_type IN ('welcome', 'job_digest', 'notification', 'other')),\n  recipient_email text NOT NULL,\n  subject text NOT NULL,\n  status text DEFAULT 'sent' NOT NULL CHECK (status IN ('sent', 'failed', 'pending', 'bounced')),\n  error_message text,\n  sent_at timestamptz DEFAULT now() NOT NULL,\n  opened_at timestamptz,\n  clicked_at timestamptz,\n  created_at timestamptz DEFAULT now() NOT NULL\n);
\n\nALTER TABLE email_logs ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Users can view own email logs"\n  ON email_logs FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "System can insert email logs"\n  ON email_logs FOR INSERT\n  TO authenticated\n  WITH CHECK (true);
\n\nCREATE POLICY "Admins can view all email logs"\n  ON email_logs FOR SELECT\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\nCREATE INDEX IF NOT EXISTS idx_email_logs_user ON email_logs(user_id);
\nCREATE INDEX IF NOT EXISTS idx_email_logs_type ON email_logs(email_type);
\nCREATE INDEX IF NOT EXISTS idx_email_logs_status ON email_logs(status);
\nCREATE INDEX IF NOT EXISTS idx_email_logs_sent_at ON email_logs(sent_at DESC);
\nCREATE INDEX IF NOT EXISTS idx_email_logs_recipient ON email_logs(recipient_email);
\n\n-- ============================================================================\n-- HELPER FUNCTIONS\n-- ============================================================================\n\n-- Function to get subscribed users for a specific domain\nCREATE OR REPLACE FUNCTION get_subscribed_users_for_domain(p_domain text)\nRETURNS TABLE (\n  user_id uuid,\n  user_email text,\n  preferred_domains text[],\n  last_sent_at timestamptz\n) AS $$\nBEGIN\n  RETURN QUERY\n  SELECT\n    s.user_id,\n    u.email as user_email,\n    s.preferred_domains,\n    s.last_sent_at\n  FROM job_notification_subscriptions s\n  JOIN auth.users u ON s.user_id = u.id\n  WHERE s.is_subscribed = true\n    AND p_domain = ANY(s.preferred_domains)\n  ORDER BY s.last_sent_at ASC NULLS FIRST;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to check if a job was already sent to a user\nCREATE OR REPLACE FUNCTION check_if_job_sent_to_user(p_user_id uuid, p_job_id uuid)\nRETURNS boolean AS $$\nBEGIN\n  RETURN EXISTS (\n    SELECT 1 FROM job_notification_logs\n    WHERE user_id = p_user_id AND job_id = p_job_id\n  );
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to log notification send\nCREATE OR REPLACE FUNCTION log_notification_send(\n  p_user_id uuid,\n  p_job_id uuid,\n  p_email_status text DEFAULT 'sent',\n  p_notification_type text DEFAULT 'daily_digest'\n)\nRETURNS uuid AS $$\nDECLARE\n  v_log_id uuid;
\nBEGIN\n  INSERT INTO job_notification_logs (user_id, job_id, email_status, notification_type)\n  VALUES (p_user_id, p_job_id, p_email_status, p_notification_type)\n  RETURNING id INTO v_log_id;
\n  \n  RETURN v_log_id;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to get notification statistics (for admin dashboard)\nCREATE OR REPLACE FUNCTION get_notification_statistics()\nRETURNS TABLE (\n  total_subscribers bigint,\n  active_subscribers bigint,\n  total_notifications_sent_today bigint,\n  total_notifications_sent_week bigint,\n  total_notifications_sent_month bigint,\n  failed_notifications_today bigint,\n  most_popular_domains jsonb\n) AS $$\nBEGIN\n  RETURN QUERY\n  SELECT\n    (SELECT COUNT(*) FROM job_notification_subscriptions)::bigint,\n    (SELECT COUNT(*) FROM job_notification_subscriptions WHERE is_subscribed = true)::bigint,\n    (SELECT COUNT(*) FROM job_notification_logs WHERE sent_at >= CURRENT_DATE)::bigint,\n    (SELECT COUNT(*) FROM job_notification_logs WHERE sent_at >= CURRENT_DATE - INTERVAL '7 days')::bigint,\n    (SELECT COUNT(*) FROM job_notification_logs WHERE sent_at >= CURRENT_DATE - INTERVAL '30 days')::bigint,\n    (SELECT COUNT(*) FROM job_notification_logs WHERE email_status = 'failed' AND sent_at >= CURRENT_DATE)::bigint,\n    (SELECT jsonb_agg(jsonb_build_object('domain', domain, 'count', count))\n     FROM (\n       SELECT UNNEST(preferred_domains) as domain, COUNT(*) as count\n       FROM job_notification_subscriptions\n       WHERE is_subscribed = true\n       GROUP BY domain\n       ORDER BY count DESC\n       LIMIT 10\n     ) domains)::jsonb;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to update last_sent_at timestamp\nCREATE OR REPLACE FUNCTION update_subscription_last_sent(p_user_id uuid)\nRETURNS void AS $$\nBEGIN\n  UPDATE job_notification_subscriptions\n  SET last_sent_at = now(), updated_at = now()\n  WHERE user_id = p_user_id;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to get jobs for daily digest (jobs posted in last 24 hours matching user preferences)\nCREATE OR REPLACE FUNCTION get_jobs_for_daily_digest(p_user_id uuid)\nRETURNS TABLE (\n  job_id uuid,\n  company_name text,\n  role_title text,\n  domain text,\n  application_link text,\n  posted_date timestamptz,\n  location_type text,\n  package_amount integer\n) AS $$\nDECLARE\n  v_preferred_domains text[];
\nBEGIN\n  -- Get user's preferred domains\n  SELECT preferred_domains INTO v_preferred_domains\n  FROM job_notification_subscriptions\n  WHERE user_id = p_user_id AND is_subscribed = true;
\n\n  -- Return jobs that match preferences and haven't been sent yet\n  RETURN QUERY\n  SELECT\n    j.id as job_id,\n    j.company_name,\n    j.role_title,\n    j.domain,\n    j.application_link,\n    j.posted_date,\n    j.location_type,\n    j.package_amount\n  FROM job_listings j\n  WHERE j.is_active = true\n    AND j.posted_date >= (CURRENT_TIMESTAMP - INTERVAL '24 hours')\n    AND j.domain = ANY(v_preferred_domains)\n    AND NOT EXISTS (\n      SELECT 1 FROM job_notification_logs\n      WHERE user_id = p_user_id AND job_id = j.id\n    )\n  ORDER BY j.posted_date DESC;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Trigger to automatically update updated_at timestamp\nCREATE OR REPLACE FUNCTION update_subscription_timestamp()\nRETURNS TRIGGER AS $$\nBEGIN\n  NEW.updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql;
\n\nDO $$ \nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_trigger \n    WHERE tgname = 'update_subscription_timestamp_trigger'\n  ) THEN\n    CREATE TRIGGER update_subscription_timestamp_trigger\n      BEFORE UPDATE ON job_notification_subscriptions\n      FOR EACH ROW\n      EXECUTE FUNCTION update_subscription_timestamp();
\n  END IF;
\nEND $$;
\n\n-- Function to cleanup old notification logs (older than 90 days)\nCREATE OR REPLACE FUNCTION cleanup_old_notification_logs()\nRETURNS void AS $$\nBEGIN\n  DELETE FROM job_notification_logs\n  WHERE sent_at < (CURRENT_TIMESTAMP - INTERVAL '90 days');
\n  \n  DELETE FROM email_logs\n  WHERE sent_at < (CURRENT_TIMESTAMP - INTERVAL '90 days');
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\nGRANT EXECUTE ON FUNCTION get_subscribed_users_for_domain(text) TO authenticated;
\nGRANT EXECUTE ON FUNCTION check_if_job_sent_to_user(uuid, uuid) TO authenticated;
\nGRANT EXECUTE ON FUNCTION log_notification_send(uuid, uuid, text, text) TO authenticated;
\nGRANT EXECUTE ON FUNCTION get_notification_statistics() TO authenticated;
\nGRANT EXECUTE ON FUNCTION update_subscription_last_sent(uuid) TO authenticated;
\nGRANT EXECUTE ON FUNCTION get_jobs_for_daily_digest(uuid) TO authenticated;
\nGRANT EXECUTE ON FUNCTION cleanup_old_notification_logs() TO authenticated;
;
