\n\n-- Add referral_code column to user_profiles\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' AND column_name = 'referral_code'\n  ) THEN\n    ALTER TABLE public.user_profiles ADD COLUMN referral_code TEXT UNIQUE;
\n  END IF;
\nEND $$;
\n\n-- Add referred_by column to track who referred this user\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' AND column_name = 'referred_by'\n  ) THEN\n    ALTER TABLE public.user_profiles ADD COLUMN referred_by TEXT;
\n  END IF;
\nEND $$;
\n\n-- Create function to generate unique referral codes\nCREATE OR REPLACE FUNCTION generate_referral_code()\nRETURNS TEXT AS $$\nDECLARE\n    characters TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
\n    code TEXT := '';
\n    i INTEGER;
\n    code_exists BOOLEAN := TRUE;
\nBEGIN\n    WHILE code_exists LOOP\n        code := '';
\n        -- Generate 8-character code\n        FOR i IN 1..8 LOOP\n            code := code || substr(characters, floor(random() * length(characters) + 1)::INTEGER, 1);
\n        END LOOP;
\n        \n        -- Check if code already exists\n        SELECT EXISTS(\n            SELECT 1 FROM public.user_profiles WHERE referral_code = code\n        ) INTO code_exists;
\n    END LOOP;
\n    \n    RETURN code;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Create function to assign referral code to user\nCREATE OR REPLACE FUNCTION assign_referral_code(user_uuid UUID)\nRETURNS TEXT AS $$\nDECLARE\n    new_code TEXT;
\nBEGIN\n    -- Generate new referral code\n    new_code := generate_referral_code();
\n    \n    -- Update user profile with referral code\n    UPDATE public.user_profiles \n    SET referral_code = new_code\n    WHERE id = user_uuid AND referral_code IS NULL;
\n    \n    RETURN new_code;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Create trigger function to auto-assign referral codes\nCREATE OR REPLACE FUNCTION auto_assign_referral_code()\nRETURNS TRIGGER AS $$\nBEGIN\n    -- Only assign if referral_code is null\n    IF NEW.referral_code IS NULL THEN\n        NEW.referral_code := generate_referral_code();
\n    END IF;
\n    \n    RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql;
\n\n-- Create trigger on user_profiles insert\nDROP TRIGGER IF EXISTS trigger_auto_assign_referral_code ON public.user_profiles;
\nCREATE TRIGGER trigger_auto_assign_referral_code\n    BEFORE INSERT ON public.user_profiles\n    FOR EACH ROW\n    EXECUTE FUNCTION auto_assign_referral_code();
\n\n-- Update existing users without referral codes\nUPDATE public.user_profiles \nSET referral_code = generate_referral_code()\nWHERE referral_code IS NULL;
\n\n-- Create index for faster referral code lookups\nCREATE INDEX IF NOT EXISTS idx_user_profiles_referral_code \nON public.user_profiles(referral_code);
\n\nCREATE INDEX IF NOT EXISTS idx_user_profiles_referred_by \nON public.user_profiles(referred_by);
;
