/*\n  # Optimize Remaining RLS Policies - Part 1\n  \n  ## Overview\n  Continues RLS policy optimization by replacing auth.uid() with (SELECT auth.uid())\n  for improved performance at scale.\n  \n  ## Tables Optimized (Part 1 of 4)\n  - user_profiles (6 policies)\n  - linkedin_profile_optimizations (4 policies)\n  - portfolio_data (6 policies)\n  - portfolio_templates (6 policies)\n  - portfolio_deployments (5 policies)\n  - ai_job_recommendations (3 policies)\n  - user_job_preferences (4 policies)\n  - wallet_transactions (2 policies)\n  - survey_subscriptions (3 policies)\n  - survey_payment_transactions (2 policies)\n  - user_addon_credits (2 policies)\n  - mock_interview_sessions (4 policies)\n  - interview_questions (2 policies)\n  - interview_responses (4 policies)\n*/\n\n-- ============================================================================\n-- USER_PROFILES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can read own profile" ON public.user_profiles;
\nDROP POLICY IF EXISTS "Users can update own profile" ON public.user_profiles;
\nDROP POLICY IF EXISTS "Users can insert own profile" ON public.user_profiles;
\nDROP POLICY IF EXISTS "Admins can read all profiles" ON public.user_profiles;
\nDROP POLICY IF EXISTS "Admins can update all profiles" ON public.user_profiles;
\nDROP POLICY IF EXISTS "Admins can insert profiles" ON public.user_profiles;
\n\nCREATE POLICY "Users can read own profile" ON public.user_profiles\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = id);
\n\nCREATE POLICY "Users can update own profile" ON public.user_profiles\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = id)\n  WITH CHECK ((SELECT auth.uid()) = id);
\n\nCREATE POLICY "Users can insert own profile" ON public.user_profiles\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = id);
\n\nCREATE POLICY "Admins can read all profiles" ON public.user_profiles\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can update all profiles" ON public.user_profiles\n  FOR UPDATE TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can insert profiles" ON public.user_profiles\n  FOR INSERT TO authenticated\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- LINKEDIN_PROFILE_OPTIMIZATIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can read own linkedin profile optimizations" ON public.linkedin_profile_optimizations;
\nDROP POLICY IF EXISTS "Users can create linkedin profile optimizations" ON public.linkedin_profile_optimizations;
\nDROP POLICY IF EXISTS "Users can update own linkedin profile optimizations" ON public.linkedin_profile_optimizations;
\nDROP POLICY IF EXISTS "Users can delete own linkedin profile optimizations" ON public.linkedin_profile_optimizations;
\n\nCREATE POLICY "Users can read own linkedin profile optimizations" ON public.linkedin_profile_optimizations\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create linkedin profile optimizations" ON public.linkedin_profile_optimizations\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own linkedin profile optimizations" ON public.linkedin_profile_optimizations\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own linkedin profile optimizations" ON public.linkedin_profile_optimizations\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- PORTFOLIO_DATA TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own portfolio data" ON public.portfolio_data;
\nDROP POLICY IF EXISTS "Users can insert own portfolio data" ON public.portfolio_data;
\nDROP POLICY IF EXISTS "Users can update own portfolio data" ON public.portfolio_data;
\nDROP POLICY IF EXISTS "Users can delete own portfolio data" ON public.portfolio_data;
\nDROP POLICY IF EXISTS "Admins can view all portfolio data" ON public.portfolio_data;
\n\nCREATE POLICY "Users can view own portfolio data" ON public.portfolio_data\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own portfolio data" ON public.portfolio_data\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own portfolio data" ON public.portfolio_data\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own portfolio data" ON public.portfolio_data\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Admins can view all portfolio data" ON public.portfolio_data\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- PORTFOLIO_TEMPLATES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own templates" ON public.portfolio_templates;
\nDROP POLICY IF EXISTS "Users can insert own templates" ON public.portfolio_templates;
\nDROP POLICY IF EXISTS "Users can update own templates" ON public.portfolio_templates;
\nDROP POLICY IF EXISTS "Users can delete own templates" ON public.portfolio_templates;
\nDROP POLICY IF EXISTS "Admins can view all templates" ON public.portfolio_templates;
\n\nCREATE POLICY "Users can view own templates" ON public.portfolio_templates\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own templates" ON public.portfolio_templates\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own templates" ON public.portfolio_templates\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own templates" ON public.portfolio_templates\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Admins can view all templates" ON public.portfolio_templates\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- PORTFOLIO_DEPLOYMENTS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own deployments" ON public.portfolio_deployments;
\nDROP POLICY IF EXISTS "Users can insert own deployments" ON public.portfolio_deployments;
\nDROP POLICY IF EXISTS "Users can update own deployments" ON public.portfolio_deployments;
\nDROP POLICY IF EXISTS "Users can delete own deployments" ON public.portfolio_deployments;
\nDROP POLICY IF EXISTS "Admins can view all deployments" ON public.portfolio_deployments;
\n\nCREATE POLICY "Users can view own deployments" ON public.portfolio_deployments\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own deployments" ON public.portfolio_deployments\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own deployments" ON public.portfolio_deployments\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own deployments" ON public.portfolio_deployments\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Admins can view all deployments" ON public.portfolio_deployments\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- AI_JOB_RECOMMENDATIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own recommendations" ON public.ai_job_recommendations;
\nDROP POLICY IF EXISTS "Users can insert own recommendations" ON public.ai_job_recommendations;
\nDROP POLICY IF EXISTS "Users can update own recommendations" ON public.ai_job_recommendations;
\nDROP POLICY IF EXISTS "Admins can view all recommendations" ON public.ai_job_recommendations;
\n\nCREATE POLICY "Users can view own recommendations" ON public.ai_job_recommendations\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own recommendations" ON public.ai_job_recommendations\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own recommendations" ON public.ai_job_recommendations\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Admins can view all recommendations" ON public.ai_job_recommendations\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- USER_JOB_PREFERENCES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own preferences" ON public.user_job_preferences;
\nDROP POLICY IF EXISTS "Users can insert own preferences" ON public.user_job_preferences;
\nDROP POLICY IF EXISTS "Users can update own preferences" ON public.user_job_preferences;
\nDROP POLICY IF EXISTS "Users can delete own preferences" ON public.user_job_preferences;
\n\nCREATE POLICY "Users can view own preferences" ON public.user_job_preferences\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own preferences" ON public.user_job_preferences\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own preferences" ON public.user_job_preferences\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own preferences" ON public.user_job_preferences\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- WALLET_TRANSACTIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view their own wallet transactions" ON public.wallet_transactions;
\nDROP POLICY IF EXISTS "System can insert transactions" ON public.wallet_transactions;
\n\nCREATE POLICY "Users can view their own wallet transactions" ON public.wallet_transactions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id OR (SELECT auth.uid()) = source_user_id);
\n\nCREATE POLICY "System can insert transactions" ON public.wallet_transactions\n  FOR INSERT TO authenticated\n  WITH CHECK (true);
\n\n-- ============================================================================\n-- SURVEY_SUBSCRIPTIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own survey subscriptions" ON public.survey_subscriptions;
\nDROP POLICY IF EXISTS "Users can create own survey subscriptions" ON public.survey_subscriptions;
\nDROP POLICY IF EXISTS "Users can update own survey subscriptions" ON public.survey_subscriptions;
\n\nCREATE POLICY "Users can view own survey subscriptions" ON public.survey_subscriptions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own survey subscriptions" ON public.survey_subscriptions\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own survey subscriptions" ON public.survey_subscriptions\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- SURVEY_PAYMENT_TRANSACTIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own survey transactions" ON public.survey_payment_transactions;
\nDROP POLICY IF EXISTS "Users can create own survey transactions" ON public.survey_payment_transactions;
\n\nCREATE POLICY "Users can view own survey transactions" ON public.survey_payment_transactions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own survey transactions" ON public.survey_payment_transactions\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- USER_ADDON_CREDITS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view their own add-on credits" ON public.user_addon_credits;
\nDROP POLICY IF EXISTS "Users can update their own add-on credits" ON public.user_addon_credits;
\n\nCREATE POLICY "Users can view their own add-on credits" ON public.user_addon_credits\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update their own add-on credits" ON public.user_addon_credits\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- MOCK_INTERVIEW_SESSIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own interview sessions" ON public.mock_interview_sessions;
\nDROP POLICY IF EXISTS "Users can create own interview sessions" ON public.mock_interview_sessions;
\nDROP POLICY IF EXISTS "Users can update own interview sessions" ON public.mock_interview_sessions;
\nDROP POLICY IF EXISTS "Admins can view all interview sessions" ON public.mock_interview_sessions;
\n\nCREATE POLICY "Users can view own interview sessions" ON public.mock_interview_sessions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own interview sessions" ON public.mock_interview_sessions\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own interview sessions" ON public.mock_interview_sessions\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Admins can view all interview sessions" ON public.mock_interview_sessions\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- INTERVIEW_QUESTIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Admins can insert interview questions" ON public.interview_questions;
\nDROP POLICY IF EXISTS "Admins can update interview questions" ON public.interview_questions;
\n\nCREATE POLICY "Admins can insert interview questions" ON public.interview_questions\n  FOR INSERT TO authenticated\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can update interview questions" ON public.interview_questions\n  FOR UPDATE TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- INTERVIEW_RESPONSES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own interview responses" ON public.interview_responses;
\nDROP POLICY IF EXISTS "Users can create own interview responses" ON public.interview_responses;
\nDROP POLICY IF EXISTS "Users can update own interview responses" ON public.interview_responses;
\nDROP POLICY IF EXISTS "Admins can view all interview responses" ON public.interview_responses;
\n\nCREATE POLICY "Users can view own interview responses" ON public.interview_responses\n  FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.mock_interview_sessions\n    WHERE mock_interview_sessions.id = interview_responses.session_id\n    AND mock_interview_sessions.user_id = (SELECT auth.uid())\n  ));
\n\nCREATE POLICY "Users can create own interview responses" ON public.interview_responses\n  FOR INSERT TO authenticated\n  WITH CHECK (EXISTS (\n    SELECT 1 FROM public.mock_interview_sessions\n    WHERE mock_interview_sessions.id = interview_responses.session_id\n    AND mock_interview_sessions.user_id = (SELECT auth.uid())\n  ));
\n\nCREATE POLICY "Users can update own interview responses" ON public.interview_responses\n  FOR UPDATE TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.mock_interview_sessions\n    WHERE mock_interview_sessions.id = interview_responses.session_id\n    AND mock_interview_sessions.user_id = (SELECT auth.uid())\n  ))\n  WITH CHECK (EXISTS (\n    SELECT 1 FROM public.mock_interview_sessions\n    WHERE mock_interview_sessions.id = interview_responses.session_id\n    AND mock_interview_sessions.user_id = (SELECT auth.uid())\n  ));
\n\nCREATE POLICY "Admins can view all interview responses" ON public.interview_responses\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n;
