\n\n-- Create user_devices table\nCREATE TABLE IF NOT EXISTS user_devices (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE NOT NULL,\n  device_fingerprint text NOT NULL,\n  device_name text,\n  device_type text, -- 'desktop', 'mobile', 'tablet'\n  browser_name text,\n  browser_version text,\n  os_name text,\n  os_version text,\n  screen_resolution text,\n  timezone text,\n  language text,\n  is_trusted boolean DEFAULT false NOT NULL,\n  is_active boolean DEFAULT true NOT NULL,\n  last_seen_at timestamptz DEFAULT now() NOT NULL,\n  last_ip_address inet,\n  last_location jsonb, -- {country, region, city, lat, lng}\n  created_at timestamptz DEFAULT now() NOT NULL,\n  updated_at timestamptz DEFAULT now() NOT NULL,\n  \n  UNIQUE(user_id, device_fingerprint)\n);
\n\n-- Create user_sessions table\nCREATE TABLE IF NOT EXISTS user_sessions (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE NOT NULL,\n  device_id uuid REFERENCES user_devices(id) ON DELETE CASCADE NOT NULL,\n  session_token text NOT NULL,\n  refresh_token text,\n  ip_address inet NOT NULL,\n  user_agent text NOT NULL,\n  location jsonb, -- {country, region, city, lat, lng}\n  is_active boolean DEFAULT true NOT NULL,\n  expires_at timestamptz NOT NULL,\n  last_activity_at timestamptz DEFAULT now() NOT NULL,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  ended_at timestamptz,\n  end_reason text, -- 'logout', 'timeout', 'security', 'device_limit'\n  \n  UNIQUE(session_token)\n);
\n\n-- Create device_activity_logs table\nCREATE TABLE IF NOT EXISTS device_activity_logs (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE NOT NULL,\n  device_id uuid REFERENCES user_devices(id) ON DELETE CASCADE,\n  session_id uuid REFERENCES user_sessions(id) ON DELETE CASCADE,\n  activity_type text NOT NULL, -- 'login', 'logout', 'device_registered', 'device_trusted', 'suspicious_activity'\n  activity_details jsonb,\n  ip_address inet,\n  location jsonb,\n  user_agent text,\n  risk_score integer DEFAULT 0, -- 0-100, higher = more suspicious\n  created_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Enable Row Level Security\nALTER TABLE user_devices ENABLE ROW LEVEL SECURITY;
\nALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;
\nALTER TABLE device_activity_logs ENABLE ROW LEVEL SECURITY;
\n\n-- Create policies for user_devices\nCREATE POLICY "Users can view own devices"\n  ON user_devices\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "Users can update own devices"\n  ON user_devices\n  FOR UPDATE\n  TO authenticated\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "System can manage devices"\n  ON user_devices\n  FOR ALL\n  TO service_role\n  USING (true);
\n\n-- Create policies for user_sessions\nCREATE POLICY "Users can view own sessions"\n  ON user_sessions\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "System can manage sessions"\n  ON user_sessions\n  FOR ALL\n  TO service_role\n  USING (true);
\n\n-- Create policies for device_activity_logs\nCREATE POLICY "Users can view own activity logs"\n  ON device_activity_logs\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "System can manage activity logs"\n  ON device_activity_logs\n  FOR ALL\n  TO service_role\n  USING (true);
\n\n-- Create indexes for performance\nCREATE INDEX IF NOT EXISTS user_devices_user_id_idx ON user_devices(user_id);
\nCREATE INDEX IF NOT EXISTS user_devices_fingerprint_idx ON user_devices(device_fingerprint);
\nCREATE INDEX IF NOT EXISTS user_devices_last_seen_idx ON user_devices(last_seen_at);
\nCREATE INDEX IF NOT EXISTS user_devices_is_active_idx ON user_devices(is_active);
\n\nCREATE INDEX IF NOT EXISTS user_sessions_user_id_idx ON user_sessions(user_id);
\nCREATE INDEX IF NOT EXISTS user_sessions_device_id_idx ON user_sessions(device_id);
\nCREATE INDEX IF NOT EXISTS user_sessions_token_idx ON user_sessions(session_token);
\nCREATE INDEX IF NOT EXISTS user_sessions_active_idx ON user_sessions(is_active);
\nCREATE INDEX IF NOT EXISTS user_sessions_expires_idx ON user_sessions(expires_at);
\n\nCREATE INDEX IF NOT EXISTS device_activity_logs_user_id_idx ON device_activity_logs(user_id);
\nCREATE INDEX IF NOT EXISTS device_activity_logs_device_id_idx ON device_activity_logs(device_id);
\nCREATE INDEX IF NOT EXISTS device_activity_logs_type_idx ON device_activity_logs(activity_type);
\nCREATE INDEX IF NOT EXISTS device_activity_logs_created_idx ON device_activity_logs(created_at);
\nCREATE INDEX IF NOT EXISTS device_activity_logs_risk_idx ON device_activity_logs(risk_score);
\n\n-- Function to update device timestamp\nCREATE OR REPLACE FUNCTION update_device_timestamp()\nRETURNS TRIGGER AS $$\nBEGIN\n  NEW.updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ language 'plpgsql';
\n\n-- Trigger for device timestamp updates\nCREATE TRIGGER update_user_devices_timestamp\n  BEFORE UPDATE ON user_devices\n  FOR EACH ROW\n  EXECUTE FUNCTION update_device_timestamp();
\n\n-- Function to generate device fingerprint\nCREATE OR REPLACE FUNCTION generate_device_fingerprint(\n  user_agent_param text,\n  screen_resolution_param text,\n  timezone_param text,\n  language_param text\n)\nRETURNS text AS $$\nBEGIN\n  RETURN encode(\n    digest(\n      COALESCE(user_agent_param, '') || '|' ||\n      COALESCE(screen_resolution_param, '') || '|' ||\n      COALESCE(timezone_param, '') || '|' ||\n      COALESCE(language_param, ''),\n      'sha256'\n    ),\n    'hex'\n  );
\nEND;
\n$$ LANGUAGE plpgsql;
\n\n-- Function to register or update device\nCREATE OR REPLACE FUNCTION register_device(\n  user_uuid uuid,\n  device_fingerprint_param text,\n  device_name_param text DEFAULT NULL,\n  device_type_param text DEFAULT NULL,\n  browser_name_param text DEFAULT NULL,\n  browser_version_param text DEFAULT NULL,\n  os_name_param text DEFAULT NULL,\n  os_version_param text DEFAULT NULL,\n  screen_resolution_param text DEFAULT NULL,\n  timezone_param text DEFAULT NULL,\n  language_param text DEFAULT NULL,\n  ip_address_param inet DEFAULT NULL,\n  location_param jsonb DEFAULT NULL\n)\nRETURNS uuid AS $$\nDECLARE\n  device_id uuid;
\nBEGIN\n  -- Insert or update device\n  INSERT INTO user_devices (\n    user_id,\n    device_fingerprint,\n    device_name,\n    device_type,\n    browser_name,\n    browser_version,\n    os_name,\n    os_version,\n    screen_resolution,\n    timezone,\n    language,\n    last_seen_at,\n    last_ip_address,\n    last_location\n  )\n  VALUES (\n    user_uuid,\n    device_fingerprint_param,\n    device_name_param,\n    device_type_param,\n    browser_name_param,\n    browser_version_param,\n    os_name_param,\n    os_version_param,\n    screen_resolution_param,\n    timezone_param,\n    language_param,\n    now(),\n    ip_address_param,\n    location_param\n  )\n  ON CONFLICT (user_id, device_fingerprint)\n  DO UPDATE SET\n    device_name = COALESCE(EXCLUDED.device_name, user_devices.device_name),\n    device_type = COALESCE(EXCLUDED.device_type, user_devices.device_type),\n    browser_name = COALESCE(EXCLUDED.browser_name, user_devices.browser_name),\n    browser_version = COALESCE(EXCLUDED.browser_version, user_devices.browser_version),\n    os_name = COALESCE(EXCLUDED.os_name, user_devices.os_name),\n    os_version = COALESCE(EXCLUDED.os_version, user_devices.os_version),\n    screen_resolution = COALESCE(EXCLUDED.screen_resolution, user_devices.screen_resolution),\n    timezone = COALESCE(EXCLUDED.timezone, user_devices.timezone),\n    language = COALESCE(EXCLUDED.language, user_devices.language),\n    last_seen_at = now(),\n    last_ip_address = COALESCE(EXCLUDED.last_ip_address, user_devices.last_ip_address),\n    last_location = COALESCE(EXCLUDED.last_location, user_devices.last_location),\n    is_active = true,\n    updated_at = now()\n  RETURNING id INTO device_id;
\n\n  RETURN device_id;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to create session\nCREATE OR REPLACE FUNCTION create_session(\n  user_uuid uuid,\n  device_uuid uuid,\n  session_token_param text,\n  refresh_token_param text DEFAULT NULL,\n  ip_address_param inet DEFAULT NULL,\n  user_agent_param text DEFAULT NULL,\n  location_param jsonb DEFAULT NULL,\n  expires_at_param timestamptz DEFAULT NULL\n)\nRETURNS uuid AS $$\nDECLARE\n  session_id uuid;
\n  max_sessions integer := 5;
 -- Maximum sessions per user\n  session_count integer;
\nBEGIN\n  -- Check current active session count\n  SELECT COUNT(*) INTO session_count\n  FROM user_sessions\n  WHERE user_id = user_uuid AND is_active = true;
\n\n  -- If at limit, end oldest session\n  IF session_count >= max_sessions THEN\n    UPDATE user_sessions\n    SET is_active = false,\n        ended_at = now(),\n        end_reason = 'device_limit'\n    WHERE id = (\n      SELECT id FROM user_sessions\n      WHERE user_id = user_uuid AND is_active = true\n      ORDER BY last_activity_at ASC\n      LIMIT 1\n    );
\n  END IF;
\n\n  -- Create new session\n  INSERT INTO user_sessions (\n    user_id,\n    device_id,\n    session_token,\n    refresh_token,\n    ip_address,\n    user_agent,\n    location,\n    expires_at\n  )\n  VALUES (\n    user_uuid,\n    device_uuid,\n    session_token_param,\n    refresh_token_param,\n    ip_address_param,\n    user_agent_param,\n    location_param,\n    COALESCE(expires_at_param, now() + interval '24 hours')\n  )\n  RETURNING id INTO session_id;
\n\n  RETURN session_id;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to end session (fixed version without GET DIAGNOSTICS)\nCREATE OR REPLACE FUNCTION end_session(\n  session_token_param text,\n  end_reason_param text DEFAULT 'logout'\n)\nRETURNS boolean AS $$\nDECLARE\n  updated_count integer;
\nBEGIN\n  -- Update the session and count affected rows\n  WITH updated_sessions AS (\n    UPDATE user_sessions\n    SET is_active = false,\n        ended_at = now(),\n        end_reason = end_reason_param\n    WHERE session_token = session_token_param AND is_active = true\n    RETURNING id\n  )\n  SELECT COUNT(*) INTO updated_count FROM updated_sessions;
\n\n  -- Return true if at least one row was updated\n  RETURN updated_count > 0;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to log device activity\nCREATE OR REPLACE FUNCTION log_device_activity(\n  user_uuid uuid,\n  device_uuid uuid DEFAULT NULL,\n  session_uuid uuid DEFAULT NULL,\n  activity_type_param text DEFAULT NULL,\n  activity_details_param jsonb DEFAULT NULL,\n  ip_address_param inet DEFAULT NULL,\n  location_param jsonb DEFAULT NULL,\n  user_agent_param text DEFAULT NULL,\n  risk_score_param integer DEFAULT 0\n)\nRETURNS uuid AS $$\nDECLARE\n  log_id uuid;
\nBEGIN\n  INSERT INTO device_activity_logs (\n    user_id,\n    device_id,\n    session_id,\n    activity_type,\n    activity_details,\n    ip_address,\n    location,\n    user_agent,\n    risk_score\n  )\n  VALUES (\n    user_uuid,\n    device_uuid,\n    session_uuid,\n    activity_type_param,\n    activity_details_param,\n    ip_address_param,\n    location_param,\n    user_agent_param,\n    risk_score_param\n  )\n  RETURNING id INTO log_id;
\n\n  RETURN log_id;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to get user's active devices\nCREATE OR REPLACE FUNCTION get_user_devices(user_uuid uuid)\nRETURNS TABLE (\n  device_id uuid,\n  device_name text,\n  device_type text,\n  browser_name text,\n  os_name text,\n  is_trusted boolean,\n  last_seen_at timestamptz,\n  last_location jsonb,\n  active_sessions integer\n) AS $$\nBEGIN\n  RETURN QUERY\n  SELECT \n    d.id,\n    d.device_name,\n    d.device_type,\n    d.browser_name,\n    d.os_name,\n    d.is_trusted,\n    d.last_seen_at,\n    d.last_location,\n    COALESCE(s.session_count, 0)::integer\n  FROM user_devices d\n  LEFT JOIN (\n    SELECT \n      device_id,\n      COUNT(*) as session_count\n    FROM user_sessions\n    WHERE is_active = true\n    GROUP BY device_id\n  ) s ON d.id = s.device_id\n  WHERE d.user_id = user_uuid AND d.is_active = true\n  ORDER BY d.last_seen_at DESC;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to detect suspicious activity\nCREATE OR REPLACE FUNCTION detect_suspicious_activity(\n  user_uuid uuid,\n  ip_address_param inet,\n  location_param jsonb,\n  user_agent_param text\n)\nRETURNS integer AS $$\nDECLARE\n  risk_score integer := 0;
\n  recent_locations jsonb[];
\n  location_count integer;
\n  recent_ips inet[];
\n  ip_count integer;
\nBEGIN\n  -- Check for multiple locations in short time\n  SELECT array_agg(DISTINCT last_location) INTO recent_locations\n  FROM user_devices\n  WHERE user_id = user_uuid \n    AND last_seen_at > now() - interval '1 hour'\n    AND last_location IS NOT NULL;
\n\n  location_count := array_length(recent_locations, 1);
\n  IF location_count > 2 THEN\n    risk_score := risk_score + 30;
\n  END IF;
\n\n  -- Check for multiple IP addresses\n  SELECT array_agg(DISTINCT last_ip_address) INTO recent_ips\n  FROM user_devices\n  WHERE user_id = user_uuid \n    AND last_seen_at > now() - interval '1 hour'\n    AND last_ip_address IS NOT NULL;
\n\n  ip_count := array_length(recent_ips, 1);
\n  IF ip_count > 3 THEN\n    risk_score := risk_score + 25;
\n  END IF;
\n\n  -- Check for new device\n  IF NOT EXISTS (\n    SELECT 1 FROM user_devices\n    WHERE user_id = user_uuid \n      AND last_ip_address = ip_address_param\n      AND created_at < now() - interval '1 day'\n  ) THEN\n    risk_score := risk_score + 20;
\n  END IF;
\n\n  -- Check for unusual time (outside normal hours)\n  IF EXTRACT(hour FROM now()) < 6 OR EXTRACT(hour FROM now()) > 23 THEN\n    risk_score := risk_score + 15;
\n  END IF;
\n\n  RETURN LEAST(risk_score, 100);
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to end all sessions for a user except current\nCREATE OR REPLACE FUNCTION end_other_sessions(\n  user_uuid uuid,\n  current_session_token text\n)\nRETURNS integer AS $$\nDECLARE\n  ended_count integer;
\nBEGIN\n  WITH ended_sessions AS (\n    UPDATE user_sessions\n    SET is_active = false,\n        ended_at = now(),\n        end_reason = 'security'\n    WHERE user_id = user_uuid \n      AND session_token != current_session_token \n      AND is_active = true\n    RETURNING id\n  )\n  SELECT COUNT(*) INTO ended_count FROM ended_sessions;
\n\n  RETURN ended_count;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to trust/untrust device\nCREATE OR REPLACE FUNCTION set_device_trust(\n  device_uuid uuid,\n  user_uuid uuid,\n  is_trusted_param boolean\n)\nRETURNS boolean AS $$\nDECLARE\n  updated_count integer;
\nBEGIN\n  WITH updated_devices AS (\n    UPDATE user_devices\n    SET is_trusted = is_trusted_param,\n        updated_at = now()\n    WHERE id = device_uuid AND user_id = user_uuid\n    RETURNING id\n  )\n  SELECT COUNT(*) INTO updated_count FROM updated_devices;
\n\n  RETURN updated_count > 0;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to remove device and end its sessions\nCREATE OR REPLACE FUNCTION remove_device(\n  device_uuid uuid,\n  user_uuid uuid\n)\nRETURNS boolean AS $$\nDECLARE\n  device_exists boolean := false;
\nBEGIN\n  -- Check if device exists and belongs to user\n  SELECT EXISTS(\n    SELECT 1 FROM user_devices \n    WHERE id = device_uuid AND user_id = user_uuid\n  ) INTO device_exists;
\n\n  IF NOT device_exists THEN\n    RETURN false;
\n  END IF;
\n\n  -- End all active sessions for this device\n  UPDATE user_sessions\n  SET is_active = false,\n      ended_at = now(),\n      end_reason = 'device_removed'\n  WHERE device_id = device_uuid AND is_active = true;
\n\n  -- Mark device as inactive\n  UPDATE user_devices\n  SET is_active = false,\n      updated_at = now()\n  WHERE id = device_uuid;
\n\n  RETURN true;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
;
