/*\n  # Optimize Remaining RLS Policies - Final Part\n  \n  ## Tables Optimized (Final Part)\n  - gaming_companies (1 policy)\n  - game_levels (1 policy)\n  - game_sessions (3 policies)\n  - game_scores (2 policies)\n  - user_game_progress (3 policies)\n  - key_finder_sessions (3 policies)\n  - key_finder_moves (2 policies)\n  - key_finder_leaderboard (2 policies)\n  - bubble_selection_sessions (3 policies)\n  - bubble_selection_questions (3 policies)\n  - bubble_selection_leaderboard (2 policies)\n  - job_notification_subscriptions (5 policies)\n  - job_notification_logs (2 policies)\n  - email_logs (2 policies)\n  - email_queue (1 policy)\n  - email_templates (1 policy)\n  - password_reset_attempts (1 policy)\n  - optimization_sessions (3 policies)\n  - rewrite_validations (2 policies)\n  - synthesized_projects (3 policies)\n  - metric_tracking (2 policies)\n  - evidence_locked_scores (2 policies)\n  - hybrid_match_results (2 policies)\n  - keyword_context_validations (2 policies)\n  - metric_reconciliation_logs (2 policies)\n  - ats_optimization_logs (2 policies)\n  \n  ## Summary\n  This migration completes the optimization of all 200+ RLS policies in the database.\n  All policies now use (SELECT auth.uid()) for improved performance.\n*/\n\n-- ============================================================================\n-- GAMING_COMPANIES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Admins can manage gaming companies" ON public.gaming_companies;
\n\nCREATE POLICY "Admins can manage gaming companies" ON public.gaming_companies\n  FOR ALL TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- GAME_LEVELS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Admins can manage game levels" ON public.game_levels;
\n\nCREATE POLICY "Admins can manage game levels" ON public.game_levels\n  FOR ALL TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- GAME_SESSIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own game sessions" ON public.game_sessions;
\nDROP POLICY IF EXISTS "Users can create own game sessions" ON public.game_sessions;
\nDROP POLICY IF EXISTS "Users can update own game sessions" ON public.game_sessions;
\n\nCREATE POLICY "Users can view own game sessions" ON public.game_sessions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own game sessions" ON public.game_sessions\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own game sessions" ON public.game_sessions\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- GAME_SCORES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own game scores" ON public.game_scores;
\nDROP POLICY IF EXISTS "Users can create own game scores" ON public.game_scores;
\n\nCREATE POLICY "Users can view own game scores" ON public.game_scores\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own game scores" ON public.game_scores\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- USER_GAME_PROGRESS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own game progress" ON public.user_game_progress;
\nDROP POLICY IF EXISTS "Users can create own game progress" ON public.user_game_progress;
\nDROP POLICY IF EXISTS "Users can update own game progress" ON public.user_game_progress;
\n\nCREATE POLICY "Users can view own game progress" ON public.user_game_progress\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own game progress" ON public.user_game_progress\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own game progress" ON public.user_game_progress\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- KEY_FINDER_SESSIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own sessions" ON public.key_finder_sessions;
\nDROP POLICY IF EXISTS "Users can create own sessions" ON public.key_finder_sessions;
\nDROP POLICY IF EXISTS "Users can update own sessions" ON public.key_finder_sessions;
\n\nCREATE POLICY "Users can view own sessions" ON public.key_finder_sessions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own sessions" ON public.key_finder_sessions\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own sessions" ON public.key_finder_sessions\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- KEY_FINDER_MOVES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own moves" ON public.key_finder_moves;
\nDROP POLICY IF EXISTS "Users can create moves for own sessions" ON public.key_finder_moves;
\n\nCREATE POLICY "Users can view own moves" ON public.key_finder_moves\n  FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.key_finder_sessions\n    WHERE key_finder_sessions.id = key_finder_moves.session_id\n    AND key_finder_sessions.user_id = (SELECT auth.uid())\n  ));
\n\nCREATE POLICY "Users can create moves for own sessions" ON public.key_finder_moves\n  FOR INSERT TO authenticated\n  WITH CHECK (EXISTS (\n    SELECT 1 FROM public.key_finder_sessions\n    WHERE key_finder_sessions.id = key_finder_moves.session_id\n    AND key_finder_sessions.user_id = (SELECT auth.uid())\n  ));
\n\n-- ============================================================================\n-- KEY_FINDER_LEADERBOARD TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can insert own leaderboard entries" ON public.key_finder_leaderboard;
\nDROP POLICY IF EXISTS "Users can update own leaderboard entries" ON public.key_finder_leaderboard;
\n\nCREATE POLICY "Users can insert own leaderboard entries" ON public.key_finder_leaderboard\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own leaderboard entries" ON public.key_finder_leaderboard\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- BUBBLE_SELECTION_SESSIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own sessions" ON public.bubble_selection_sessions;
\nDROP POLICY IF EXISTS "Users can create own sessions" ON public.bubble_selection_sessions;
\nDROP POLICY IF EXISTS "Users can update own sessions" ON public.bubble_selection_sessions;
\n\nCREATE POLICY "Users can view own sessions" ON public.bubble_selection_sessions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own sessions" ON public.bubble_selection_sessions\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own sessions" ON public.bubble_selection_sessions\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- BUBBLE_SELECTION_QUESTIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own questions" ON public.bubble_selection_questions;
\nDROP POLICY IF EXISTS "Users can create questions for own sessions" ON public.bubble_selection_questions;
\nDROP POLICY IF EXISTS "Users can update own questions" ON public.bubble_selection_questions;
\n\nCREATE POLICY "Users can view own questions" ON public.bubble_selection_questions\n  FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.bubble_selection_sessions\n    WHERE bubble_selection_sessions.id = bubble_selection_questions.session_id\n    AND bubble_selection_sessions.user_id = (SELECT auth.uid())\n  ));
\n\nCREATE POLICY "Users can create questions for own sessions" ON public.bubble_selection_questions\n  FOR INSERT TO authenticated\n  WITH CHECK (EXISTS (\n    SELECT 1 FROM public.bubble_selection_sessions\n    WHERE bubble_selection_sessions.id = bubble_selection_questions.session_id\n    AND bubble_selection_sessions.user_id = (SELECT auth.uid())\n  ));
\n\nCREATE POLICY "Users can update own questions" ON public.bubble_selection_questions\n  FOR UPDATE TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.bubble_selection_sessions\n    WHERE bubble_selection_sessions.id = bubble_selection_questions.session_id\n    AND bubble_selection_sessions.user_id = (SELECT auth.uid())\n  ))\n  WITH CHECK (EXISTS (\n    SELECT 1 FROM public.bubble_selection_sessions\n    WHERE bubble_selection_sessions.id = bubble_selection_questions.session_id\n    AND bubble_selection_sessions.user_id = (SELECT auth.uid())\n  ));
\n\n-- ============================================================================\n-- BUBBLE_SELECTION_LEADERBOARD TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can insert own leaderboard entries" ON public.bubble_selection_leaderboard;
\nDROP POLICY IF EXISTS "Users can update own leaderboard entries" ON public.bubble_selection_leaderboard;
\n\nCREATE POLICY "Users can insert own leaderboard entries" ON public.bubble_selection_leaderboard\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own leaderboard entries" ON public.bubble_selection_leaderboard\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- JOB_NOTIFICATION_SUBSCRIPTIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own subscription" ON public.job_notification_subscriptions;
\nDROP POLICY IF EXISTS "Users can insert own subscription" ON public.job_notification_subscriptions;
\nDROP POLICY IF EXISTS "Users can update own subscription" ON public.job_notification_subscriptions;
\nDROP POLICY IF EXISTS "Users can delete own subscription" ON public.job_notification_subscriptions;
\nDROP POLICY IF EXISTS "Admins can view all subscriptions" ON public.job_notification_subscriptions;
\n\nCREATE POLICY "Users can view own subscription" ON public.job_notification_subscriptions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own subscription" ON public.job_notification_subscriptions\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own subscription" ON public.job_notification_subscriptions\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own subscription" ON public.job_notification_subscriptions\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Admins can view all subscriptions" ON public.job_notification_subscriptions\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- JOB_NOTIFICATION_LOGS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own notification logs" ON public.job_notification_logs;
\nDROP POLICY IF EXISTS "Admins can view all notification logs" ON public.job_notification_logs;
\n\nCREATE POLICY "Users can view own notification logs" ON public.job_notification_logs\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Admins can view all notification logs" ON public.job_notification_logs\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- EMAIL_LOGS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own email logs" ON public.email_logs;
\nDROP POLICY IF EXISTS "Admins can view all email logs" ON public.email_logs;
\n\nCREATE POLICY "Users can view own email logs" ON public.email_logs\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Admins can view all email logs" ON public.email_logs\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- EMAIL_QUEUE TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Only admins can view email queue" ON public.email_queue;
\n\nCREATE POLICY "Only admins can view email queue" ON public.email_queue\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- EMAIL_TEMPLATES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Admins can manage email templates" ON public.email_templates;
\n\nCREATE POLICY "Admins can manage email templates" ON public.email_templates\n  FOR ALL TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- PASSWORD_RESET_ATTEMPTS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Admins can view all password reset attempts" ON public.password_reset_attempts;
\n\nCREATE POLICY "Admins can view all password reset attempts" ON public.password_reset_attempts\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- OPTIMIZATION_SESSIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own optimization sessions" ON public.optimization_sessions;
\nDROP POLICY IF EXISTS "Users can create own optimization sessions" ON public.optimization_sessions;
\nDROP POLICY IF EXISTS "Users can update own optimization sessions" ON public.optimization_sessions;
\n\nCREATE POLICY "Users can view own optimization sessions" ON public.optimization_sessions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own optimization sessions" ON public.optimization_sessions\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own optimization sessions" ON public.optimization_sessions\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- REWRITE_VALIDATIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own rewrite validations" ON public.rewrite_validations;
\nDROP POLICY IF EXISTS "System can insert rewrite validations" ON public.rewrite_validations;
\n\nCREATE POLICY "Users can view own rewrite validations" ON public.rewrite_validations\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "System can insert rewrite validations" ON public.rewrite_validations\n  FOR INSERT TO authenticated\n  WITH CHECK (true);
\n\n-- ============================================================================\n-- SYNTHESIZED_PROJECTS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own synthesized projects" ON public.synthesized_projects;
\nDROP POLICY IF EXISTS "Users can create synthesized projects" ON public.synthesized_projects;
\nDROP POLICY IF EXISTS "Users can update own synthesized projects" ON public.synthesized_projects;
\n\nCREATE POLICY "Users can view own synthesized projects" ON public.synthesized_projects\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create synthesized projects" ON public.synthesized_projects\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own synthesized projects" ON public.synthesized_projects\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- METRIC_TRACKING TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own metric tracking" ON public.metric_tracking;
\nDROP POLICY IF EXISTS "System can track metrics" ON public.metric_tracking;
\n\nCREATE POLICY "Users can view own metric tracking" ON public.metric_tracking\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "System can track metrics" ON public.metric_tracking\n  FOR INSERT TO authenticated\n  WITH CHECK (true);
\n\n-- ============================================================================\n-- EVIDENCE_LOCKED_SCORES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own evidence scores" ON public.evidence_locked_scores;
\nDROP POLICY IF EXISTS "Users can insert own evidence scores" ON public.evidence_locked_scores;
\n\nCREATE POLICY "Users can view own evidence scores" ON public.evidence_locked_scores\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own evidence scores" ON public.evidence_locked_scores\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- HYBRID_MATCH_RESULTS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own hybrid matches" ON public.hybrid_match_results;
\nDROP POLICY IF EXISTS "Users can insert own hybrid matches" ON public.hybrid_match_results;
\n\nCREATE POLICY "Users can view own hybrid matches" ON public.hybrid_match_results\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own hybrid matches" ON public.hybrid_match_results\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- KEYWORD_CONTEXT_VALIDATIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own keyword validations" ON public.keyword_context_validations;
\nDROP POLICY IF EXISTS "Users can insert own keyword validations" ON public.keyword_context_validations;
\n\nCREATE POLICY "Users can view own keyword validations" ON public.keyword_context_validations\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own keyword validations" ON public.keyword_context_validations\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- METRIC_RECONCILIATION_LOGS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own metric logs" ON public.metric_reconciliation_logs;
\nDROP POLICY IF EXISTS "Users can insert own metric logs" ON public.metric_reconciliation_logs;
\n\nCREATE POLICY "Users can view own metric logs" ON public.metric_reconciliation_logs\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own metric logs" ON public.metric_reconciliation_logs\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- ATS_OPTIMIZATION_LOGS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own ATS logs" ON public.ats_optimization_logs;
\nDROP POLICY IF EXISTS "Users can insert own ATS logs" ON public.ats_optimization_logs;
\n\nCREATE POLICY "Users can view own ATS logs" ON public.ats_optimization_logs\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own ATS logs" ON public.ats_optimization_logs\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- COMPLETION SUMMARY\n-- ============================================================================\n\nCOMMENT ON SCHEMA public IS 'All RLS policies optimized. Using (SELECT auth.uid()) for improved performance at scale.';
\n;
