\n\n-- Drop existing policies if they exist\nDROP POLICY IF EXISTS "Users can read own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can update own profile" ON profiles;
\n\n-- Drop existing triggers if they exist\nDROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
\nDROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
\n\n-- Drop existing functions if they exist\nDROP FUNCTION IF EXISTS update_updated_at_column();
\nDROP FUNCTION IF EXISTS public.handle_new_user();
\n\n-- Create profiles table (will not error if exists)\nCREATE TABLE IF NOT EXISTS profiles (\n  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,\n  name text NOT NULL,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  updated_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Enable Row Level Security\nALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
\n\n-- Create policies\nCREATE POLICY "Users can read own profile"\n  ON profiles\n  FOR SELECT\n  TO authenticated\n  USING (auth.uid() = id);
\n\nCREATE POLICY "Users can insert own profile"\n  ON profiles\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = id);
\n\nCREATE POLICY "Users can update own profile"\n  ON profiles\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id)\n  WITH CHECK (auth.uid() = id);
\n\n-- Function to update timestamp\nCREATE OR REPLACE FUNCTION update_updated_at_column()\nRETURNS TRIGGER AS $$\nBEGIN\n  NEW.updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ language 'plpgsql';
\n\n-- Trigger for timestamp updates\nCREATE TRIGGER update_profiles_updated_at\n  BEFORE UPDATE ON profiles\n  FOR EACH ROW\n  EXECUTE FUNCTION update_updated_at_column();
\n\n-- Function to handle new user signup\nCREATE OR REPLACE FUNCTION public.handle_new_user()\nRETURNS TRIGGER AS $$\nBEGIN\n  INSERT INTO public.profiles (id, name, created_at, updated_at)\n  VALUES (\n    NEW.id,\n    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1), 'User'),\n    now(),\n    now()\n  )\n  ON CONFLICT (id) DO UPDATE SET\n    name = COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1), profiles.name),\n    updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Trigger for auto profile creation\nCREATE TRIGGER on_auth_user_created\n  AFTER INSERT ON auth.users\n  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
\n\n-- Create indexes (will not error if exist)\nCREATE INDEX IF NOT EXISTS profiles_id_idx ON profiles(id);
\nCREATE INDEX IF NOT EXISTS profiles_created_at_idx ON profiles(created_at);
;
