\n\n-- Create ip_coupon_usage table\nCREATE TABLE IF NOT EXISTS ip_coupon_usage (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  ip_address inet NOT NULL,\n  coupon_code text NOT NULL,\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE,\n  used_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Enable Row Level Security\nALTER TABLE ip_coupon_usage ENABLE ROW LEVEL SECURITY;
\n\n-- Create policy for service role only\nCREATE POLICY "Only service role can access IP tracking"\n  ON ip_coupon_usage\n  FOR ALL\n  TO service_role\n  USING (true);
\n\n-- Create indexes for better performance\nCREATE INDEX IF NOT EXISTS ip_coupon_usage_ip_idx ON ip_coupon_usage(ip_address);
\nCREATE INDEX IF NOT EXISTS ip_coupon_usage_coupon_idx ON ip_coupon_usage(coupon_code);
\nCREATE INDEX IF NOT EXISTS ip_coupon_usage_user_idx ON ip_coupon_usage(user_id);
\n\n-- Function to check if IP has used a specific coupon\nCREATE OR REPLACE FUNCTION has_ip_used_coupon(\n  ip_address_param inet,\n  coupon_code_param text\n)\nRETURNS boolean AS $$\nBEGIN\n  RETURN EXISTS (\n    SELECT 1 FROM ip_coupon_usage\n    WHERE ip_address = ip_address_param\n      AND coupon_code = coupon_code_param\n  );
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to check if user has used a specific coupon\nCREATE OR REPLACE FUNCTION has_user_used_coupon(\n  user_uuid uuid,\n  coupon_code_param text\n)\nRETURNS boolean AS $$\nBEGIN\n  RETURN EXISTS (\n    SELECT 1 FROM subscriptions\n    WHERE user_id = user_uuid\n      AND coupon_used = coupon_code_param\n  );
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to validate coupon eligibility\nCREATE OR REPLACE FUNCTION validate_coupon_eligibility(\n  user_uuid uuid,\n  ip_address_param inet,\n  coupon_code_param text\n)\nRETURNS TABLE (\n  is_eligible boolean,\n  message text\n) AS $$\nDECLARE\n  user_used boolean;
\n  ip_used boolean;
\nBEGIN\n  -- Check if user has used this coupon before\n  SELECT has_user_used_coupon(user_uuid, coupon_code_param) INTO user_used;
\n  \n  -- Check if IP has used this coupon before\n  SELECT has_ip_used_coupon(ip_address_param, coupon_code_param) INTO ip_used;
\n  \n  -- Determine eligibility\n  IF user_used THEN\n    RETURN QUERY SELECT false, 'You have already used this coupon code.'::text;
\n  ELSIF ip_used THEN\n    RETURN QUERY SELECT false, 'This coupon has already been used from your network.'::text;
\n  ELSE\n    RETURN QUERY SELECT true, 'Coupon is eligible for use.'::text;
\n  END IF;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
;
