/*\n  # Add Password Reset Rate Limiting System\n\n  1. New Tables\n    - `password_reset_attempts`\n      - `id` (uuid, primary key)\n      - `email` (text, indexed) - Email address requesting reset\n      - `ip_address` (text) - IP address of requester\n      - `attempted_at` (timestamptz) - Timestamp of attempt\n      - `success` (boolean) - Whether reset email was sent successfully\n      - `user_agent` (text) - Browser/device info\n\n  2. Security\n    - Enable RLS on `password_reset_attempts` table\n    - Add policy for authenticated admins to view reset attempts\n    - Add function to check rate limit (3 attempts per 15 minutes)\n    - Add cleanup function to remove old attempts (older than 24 hours)\n\n  3. Functions\n    - `check_password_reset_rate_limit` - Returns remaining time if rate limited\n    - `cleanup_old_password_reset_attempts` - Removes attempts older than 24 hours\n    - `log_password_reset_attempt` - Logs a new reset attempt\n*/\n\n-- Create password_reset_attempts table\nCREATE TABLE IF NOT EXISTS password_reset_attempts (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  email text NOT NULL,\n  ip_address text,\n  attempted_at timestamptz DEFAULT now() NOT NULL,\n  success boolean DEFAULT false NOT NULL,\n  user_agent text,\n  created_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Add indexes for performance\nCREATE INDEX IF NOT EXISTS idx_password_reset_attempts_email ON password_reset_attempts(email);
\nCREATE INDEX IF NOT EXISTS idx_password_reset_attempts_attempted_at ON password_reset_attempts(attempted_at);
\nCREATE INDEX IF NOT EXISTS idx_password_reset_attempts_ip_address ON password_reset_attempts(ip_address);
\n\n-- Enable RLS\nALTER TABLE password_reset_attempts ENABLE ROW LEVEL SECURITY;
\n\n-- Admin policy to view all attempts\nCREATE POLICY "Admins can view all password reset attempts"\n  ON password_reset_attempts\n  FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM user_profiles\n      WHERE user_profiles.id = auth.uid()\n      AND user_profiles.role = 'admin'\n    )\n  );
\n\n-- Function to check if email is rate limited\nCREATE OR REPLACE FUNCTION check_password_reset_rate_limit(\n  p_email text,\n  p_ip_address text DEFAULT NULL\n)\nRETURNS json\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  v_attempt_count integer;
\n  v_oldest_attempt timestamptz;
\n  v_time_until_allowed integer;
\n  v_rate_limit_minutes integer := 15;
\n  v_max_attempts integer := 3;
\nBEGIN\n  -- Count attempts in the last 15 minutes for this email\n  SELECT COUNT(*), MIN(attempted_at)\n  INTO v_attempt_count, v_oldest_attempt\n  FROM password_reset_attempts\n  WHERE email = p_email\n  AND attempted_at > now() - interval '15 minutes';
\n\n  -- If under the limit, allow the request\n  IF v_attempt_count < v_max_attempts THEN\n    RETURN json_build_object(\n      'allowed', true,\n      'remaining_attempts', v_max_attempts - v_attempt_count,\n      'message', 'Request allowed'\n    );
\n  END IF;
\n\n  -- Calculate time until oldest attempt expires\n  v_time_until_allowed := EXTRACT(EPOCH FROM (\n    v_oldest_attempt + interval '15 minutes' - now()\n  ))::integer;
\n\n  -- Return rate limit info\n  RETURN json_build_object(\n    'allowed', false,\n    'remaining_attempts', 0,\n    'retry_after_seconds', v_time_until_allowed,\n    'message', format('Too many password reset attempts. Please try again in %s minutes.',\n      CEIL(v_time_until_allowed / 60.0)\n    )\n  );
\nEND;
\n$$;
\n\n-- Function to log password reset attempt\nCREATE OR REPLACE FUNCTION log_password_reset_attempt(\n  p_email text,\n  p_ip_address text DEFAULT NULL,\n  p_user_agent text DEFAULT NULL,\n  p_success boolean DEFAULT true\n)\nRETURNS uuid\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  v_attempt_id uuid;
\nBEGIN\n  INSERT INTO password_reset_attempts (\n    email,\n    ip_address,\n    user_agent,\n    success,\n    attempted_at\n  ) VALUES (\n    p_email,\n    p_ip_address,\n    p_user_agent,\n    p_success,\n    now()\n  )\n  RETURNING id INTO v_attempt_id;
\n\n  RETURN v_attempt_id;
\nEND;
\n$$;
\n\n-- Function to cleanup old attempts (older than 24 hours)\nCREATE OR REPLACE FUNCTION cleanup_old_password_reset_attempts()\nRETURNS integer\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  v_deleted_count integer;
\nBEGIN\n  DELETE FROM password_reset_attempts\n  WHERE attempted_at < now() - interval '24 hours';
\n\n  GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
\n\n  RETURN v_deleted_count;
\nEND;
\n$$;
\n\n-- Create a scheduled job to cleanup old attempts daily (using pg_cron if available)\n-- Note: This is optional and requires pg_cron extension\n-- Uncomment if pg_cron is enabled:\n-- SELECT cron.schedule(\n--   'cleanup-password-reset-attempts',\n--   '0 2 * * *', -- Run at 2 AM daily\n--   $$SELECT cleanup_old_password_reset_attempts();
$$\n-- );
;
