\n\n-- Create job_listings table\nCREATE TABLE IF NOT EXISTS job_listings (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  company_name text NOT NULL,\n  company_logo_url text,\n  role_title text NOT NULL,\n  package_amount integer, -- In rupees\n  package_type text CHECK (package_type IN ('CTC', 'stipend', 'hourly')),\n  domain text NOT NULL,\n  location_type text NOT NULL CHECK (location_type IN ('Remote', 'Onsite', 'Hybrid')),\n  location_city text,\n  experience_required text NOT NULL,\n  qualification text NOT NULL,\n  short_description text NOT NULL,\n  full_description text NOT NULL,\n  application_link text NOT NULL,\n  posted_date timestamptz NOT NULL,\n  source_api text NOT NULL,\n  is_active boolean DEFAULT true NOT NULL,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  updated_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Create optimized_resumes table\nCREATE TABLE IF NOT EXISTS optimized_resumes (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE NOT NULL,\n  job_listing_id uuid REFERENCES job_listings(id) ON DELETE CASCADE NOT NULL,\n  resume_content jsonb NOT NULL,\n  pdf_url text,\n  docx_url text,\n  optimization_score integer DEFAULT 0 NOT NULL,\n  created_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Create manual_apply_logs table\nCREATE TABLE IF NOT EXISTS manual_apply_logs (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE NOT NULL,\n  job_listing_id uuid REFERENCES job_listings(id) ON DELETE CASCADE NOT NULL,\n  optimized_resume_id uuid REFERENCES optimized_resumes(id) ON DELETE CASCADE NOT NULL,\n  application_date timestamptz NOT NULL,\n  status text NOT NULL CHECK (status IN ('pending', 'submitted', 'failed')),\n  redirect_url text NOT NULL,\n  notes text,\n  created_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Create auto_apply_logs table\nCREATE TABLE IF NOT EXISTS auto_apply_logs (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE NOT NULL,\n  job_listing_id uuid REFERENCES job_listings(id) ON DELETE CASCADE NOT NULL,\n  optimized_resume_id uuid REFERENCES optimized_resumes(id) ON DELETE CASCADE NOT NULL,\n  application_date timestamptz NOT NULL,\n  status text NOT NULL CHECK (status IN ('pending', 'submitted', 'failed')),\n  screenshot_url text,\n  form_data_snapshot jsonb,\n  error_message text,\n  created_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Enable Row Level Security\nALTER TABLE job_listings ENABLE ROW LEVEL SECURITY;
\nALTER TABLE optimized_resumes ENABLE ROW LEVEL SECURITY;
\nALTER TABLE manual_apply_logs ENABLE ROW LEVEL SECURITY;
\nALTER TABLE auto_apply_logs ENABLE ROW LEVEL SECURITY;
\n\n-- Policies for job_listings (public read access)\nCREATE POLICY "Anyone can view active job listings"\n  ON job_listings\n  FOR SELECT\n  TO public\n  USING (is_active = true);
\n\nCREATE POLICY "Service role can manage job listings"\n  ON job_listings\n  FOR ALL\n  TO service_role\n  USING (true);
\n\n-- Policies for optimized_resumes\nCREATE POLICY "Users can view own optimized resumes"\n  ON optimized_resumes\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "Users can create own optimized resumes"\n  ON optimized_resumes\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "Service role can manage optimized resumes"\n  ON optimized_resumes\n  FOR ALL\n  TO service_role\n  USING (true);
\n\n-- Policies for manual_apply_logs\nCREATE POLICY "Users can view own manual apply logs"\n  ON manual_apply_logs\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "Users can create own manual apply logs"\n  ON manual_apply_logs\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "Users can update own manual apply logs"\n  ON manual_apply_logs\n  FOR UPDATE\n  TO authenticated\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());
\n\n-- Policies for auto_apply_logs\nCREATE POLICY "Users can view own auto apply logs"\n  ON auto_apply_logs\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "Users can create own auto apply logs"\n  ON auto_apply_logs\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "Users can update own auto apply logs"\n  ON auto_apply_logs\n  FOR UPDATE\n  TO authenticated\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());
\n\n-- Create indexes for performance\nCREATE INDEX IF NOT EXISTS job_listings_domain_idx ON job_listings(domain);
\nCREATE INDEX IF NOT EXISTS job_listings_location_type_idx ON job_listings(location_type);
\nCREATE INDEX IF NOT EXISTS job_listings_experience_idx ON job_listings(experience_required);
\nCREATE INDEX IF NOT EXISTS job_listings_posted_date_idx ON job_listings(posted_date);
\nCREATE INDEX IF NOT EXISTS job_listings_package_amount_idx ON job_listings(package_amount);
\nCREATE INDEX IF NOT EXISTS job_listings_active_idx ON job_listings(is_active);
\n\nCREATE INDEX IF NOT EXISTS optimized_resumes_user_id_idx ON optimized_resumes(user_id);
\nCREATE INDEX IF NOT EXISTS optimized_resumes_job_listing_id_idx ON optimized_resumes(job_listing_id);
\n\nCREATE INDEX IF NOT EXISTS manual_apply_logs_user_id_idx ON manual_apply_logs(user_id);
\nCREATE INDEX IF NOT EXISTS manual_apply_logs_job_listing_id_idx ON manual_apply_logs(job_listing_id);
\nCREATE INDEX IF NOT EXISTS manual_apply_logs_application_date_idx ON manual_apply_logs(application_date);
\n\nCREATE INDEX IF NOT EXISTS auto_apply_logs_user_id_idx ON auto_apply_logs(user_id);
\nCREATE INDEX IF NOT EXISTS auto_apply_logs_job_listing_id_idx ON auto_apply_logs(job_listing_id);
\nCREATE INDEX IF NOT EXISTS auto_apply_logs_application_date_idx ON auto_apply_logs(application_date);
\n\n-- Function to update job_listings timestamp\nCREATE OR REPLACE FUNCTION update_job_listings_timestamp()\nRETURNS TRIGGER AS $$\nBEGIN\n  NEW.updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ language 'plpgsql';
\n\n-- Trigger for job_listings timestamp updates\nCREATE TRIGGER update_job_listings_timestamp\n  BEFORE UPDATE ON job_listings\n  FOR EACH ROW\n  EXECUTE FUNCTION update_job_listings_timestamp();
\n\n-- Function to get user's application history\nCREATE OR REPLACE FUNCTION get_user_application_history(user_uuid uuid)\nRETURNS TABLE (\n  application_id uuid,\n  job_id uuid,\n  company_name text,\n  role_title text,\n  application_date timestamptz,\n  application_method text,\n  status text,\n  resume_pdf_url text,\n  screenshot_url text,\n  redirect_url text\n) AS $$\nBEGIN\n  RETURN QUERY\n  -- Manual applications\n  SELECT \n    mal.id as application_id,\n    jl.id as job_id,\n    jl.company_name,\n    jl.role_title,\n    mal.application_date,\n    'manual'::text as application_method,\n    mal.status,\n    or_manual.pdf_url as resume_pdf_url,\n    null::text as screenshot_url,\n    mal.redirect_url\n  FROM manual_apply_logs mal\n  JOIN job_listings jl ON mal.job_listing_id = jl.id\n  JOIN optimized_resumes or_manual ON mal.optimized_resume_id = or_manual.id\n  WHERE mal.user_id = user_uuid\n  \n  UNION ALL\n  \n  -- Auto applications\n  SELECT \n    aal.id as application_id,\n    jl.id as job_id,\n    jl.company_name,\n    jl.role_title,\n    aal.application_date,\n    'auto'::text as application_method,\n    aal.status,\n    or_auto.pdf_url as resume_pdf_url,\n    aal.screenshot_url,\n    null::text as redirect_url\n  FROM auto_apply_logs aal\n  JOIN job_listings jl ON aal.job_listing_id = jl.id\n  JOIN optimized_resumes or_auto ON aal.optimized_resume_id = or_auto.id\n  WHERE aal.user_id = user_uuid\n  \n  ORDER BY application_date DESC;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
;
