\n\n-- Create job_status enum if it doesn't exist\nDO $$ \nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_status') THEN\n    CREATE TYPE job_status AS ENUM (\n      'applied',\n      'interview_scheduled',\n      'interviewed',\n      'rejected',\n      'offer_received'\n    );
\n  END IF;
\nEND $$;
\n\n-- Create interview_stage enum if it doesn't exist\nDO $$ \nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'interview_stage') THEN\n    CREATE TYPE interview_stage AS ENUM (\n      'screening',\n      'technical',\n      'behavioral',\n      'final',\n      'completed'\n    );
\n  END IF;
\nEND $$;
\n\n-- Create job_applications table\nCREATE TABLE IF NOT EXISTS job_applications (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  client_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE,\n  company_name text NOT NULL,\n  job_title text NOT NULL,\n  job_url text,\n  application_date date NOT NULL,\n  status job_status DEFAULT 'applied',\n  notes text,\n  follow_up_date date,\n  created_at timestamptz DEFAULT now(),\n  updated_at timestamptz DEFAULT now()\n);
\n\n-- Create interviews table\nCREATE TABLE IF NOT EXISTS interviews (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  job_application_id uuid REFERENCES job_applications(id) ON DELETE CASCADE,\n  interview_date timestamptz,\n  interview_stage interview_stage,\n  interviewer_name text,\n  interview_notes text,\n  feedback text,\n  result text,\n  next_steps text,\n  created_at timestamptz DEFAULT now(),\n  updated_at timestamptz DEFAULT now()\n);
\n\n-- Enable Row Level Security\nALTER TABLE job_applications ENABLE ROW LEVEL SECURITY;
\nALTER TABLE interviews ENABLE ROW LEVEL SECURITY;
\n\n-- Check if policy exists before creating it\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_policies \n    WHERE tablename = 'job_applications' \n    AND policyname = 'Clients can manage their own job applications'\n  ) THEN\n    CREATE POLICY "Clients can manage their own job applications"\n      ON job_applications\n      FOR ALL\n      TO public\n      USING (\n        (client_id IN (SELECT id FROM user_profiles WHERE user_id = auth.uid()))\n        OR\n        (EXISTS (SELECT 1 FROM user_profiles WHERE user_id = auth.uid() AND role = 'admin'))\n      );
\n  END IF;
\nEND $$;
\n\n-- Create policy for interviews table\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM pg_policies \n    WHERE tablename = 'interviews'\n  ) THEN\n    CREATE POLICY "Interviews accessible through job applications"\n      ON interviews\n      FOR ALL\n      TO public\n      USING (\n        job_application_id IN (\n          SELECT id FROM job_applications \n          WHERE client_id IN (SELECT id FROM user_profiles WHERE user_id = auth.uid())\n          OR EXISTS (SELECT 1 FROM user_profiles WHERE user_id = auth.uid() AND role = 'admin')\n        )\n      );
\n  END IF;
\nEND $$;
\n\n-- Create indexes for better performance\nCREATE INDEX IF NOT EXISTS idx_job_applications_client_id ON job_applications(client_id);
\nCREATE INDEX IF NOT EXISTS idx_job_applications_status ON job_applications(status);
\nCREATE INDEX IF NOT EXISTS idx_interviews_job_application_id ON interviews(job_application_id);
\n\n-- Function to get job application statistics\nCREATE OR REPLACE FUNCTION get_job_application_stats(user_uuid uuid)\nRETURNS TABLE (\n  total_applications integer,\n  active_applications integer,\n  interviews_scheduled integer,\n  offers_received integer,\n  rejection_rate numeric\n) AS $$\nBEGIN\n  RETURN QUERY\n  WITH stats AS (\n    SELECT\n      COUNT(*) as total,\n      COUNT(*) FILTER (WHERE status IN ('applied', 'interview_scheduled', 'interviewed')) as active,\n      COUNT(*) FILTER (WHERE status = 'interview_scheduled') as interviews,\n      COUNT(*) FILTER (WHERE status = 'offer_received') as offers,\n      COUNT(*) FILTER (WHERE status = 'rejected') as rejections\n    FROM job_applications ja\n    JOIN user_profiles up ON ja.client_id = up.id\n    WHERE up.user_id = user_uuid\n  )\n  SELECT\n    total::integer,\n    active::integer,\n    interviews::integer,\n    offers::integer,\n    CASE WHEN total > 0 THEN (rejections::numeric / total::numeric) * 100 ELSE 0 END\n  FROM stats;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to get upcoming interviews\nCREATE OR REPLACE FUNCTION get_upcoming_interviews(user_uuid uuid)\nRETURNS TABLE (\n  interview_id uuid,\n  company_name text,\n  job_title text,\n  interview_date timestamptz,\n  stage interview_stage,\n  days_until integer\n) AS $$\nBEGIN\n  RETURN QUERY\n  SELECT\n    i.id,\n    ja.company_name,\n    ja.job_title,\n    i.interview_date,\n    i.interview_stage,\n    EXTRACT(DAY FROM (i.interview_date - now()))::integer as days_until\n  FROM interviews i\n  JOIN job_applications ja ON i.job_application_id = ja.id\n  JOIN user_profiles up ON ja.client_id = up.id\n  WHERE up.user_id = user_uuid\n    AND i.interview_date > now()\n  ORDER BY i.interview_date ASC;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
;
