\n\n-- Add new columns to user_profiles table\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' AND column_name = 'education_details'\n  ) THEN\n    ALTER TABLE user_profiles ADD COLUMN education_details jsonb;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' AND column_name = 'experience_details'\n  ) THEN\n    ALTER TABLE user_profiles ADD COLUMN experience_details jsonb;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' AND column_name = 'skills_details'\n  ) THEN\n    ALTER TABLE user_profiles ADD COLUMN skills_details jsonb;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' AND column_name = 'linkedin_profile_url'\n  ) THEN\n    ALTER TABLE user_profiles ADD COLUMN linkedin_profile_url text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' AND column_name = 'github_profile_url'\n  ) THEN\n    ALTER TABLE user_profiles ADD COLUMN github_profile_url text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' AND column_name = 'resume_headline'\n  ) THEN\n    ALTER TABLE user_profiles ADD COLUMN resume_headline text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' AND column_name = 'current_location'\n  ) THEN\n    ALTER TABLE user_profiles ADD COLUMN current_location text;
\n  END IF;
\nEND $$;
\n\n-- Create indexes for new fields\nCREATE INDEX IF NOT EXISTS user_profiles_linkedin_url_idx ON user_profiles(linkedin_profile_url);
\nCREATE INDEX IF NOT EXISTS user_profiles_github_url_idx ON user_profiles(github_profile_url);
\nCREATE INDEX IF NOT EXISTS user_profiles_current_location_idx ON user_profiles(current_location);
\n\n-- Function to check if user profile is complete for auto-apply\nCREATE OR REPLACE FUNCTION is_profile_complete_for_auto_apply(user_uuid uuid)\nRETURNS boolean AS $$\nDECLARE\n  profile_record user_profiles%ROWTYPE;
\nBEGIN\n  SELECT * INTO profile_record\n  FROM user_profiles\n  WHERE id = user_uuid;
\n\n  -- Check if required fields are present\n  RETURN (\n    profile_record.full_name IS NOT NULL AND\n    profile_record.email_address IS NOT NULL AND\n    profile_record.phone IS NOT NULL AND\n    profile_record.education_details IS NOT NULL AND\n    profile_record.linkedin_profile_url IS NOT NULL AND\n    profile_record.resume_headline IS NOT NULL\n  );
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to get user profile for auto-apply\nCREATE OR REPLACE FUNCTION get_user_auto_apply_profile(user_uuid uuid)\nRETURNS TABLE (\n  full_name text,\n  email_address text,\n  phone text,\n  education_details jsonb,\n  experience_details jsonb,\n  skills_details jsonb,\n  linkedin_profile_url text,\n  github_profile_url text,\n  resume_headline text,\n  current_location text\n) AS $$\nBEGIN\n  RETURN QUERY\n  SELECT \n    up.full_name,\n    up.email_address,\n    up.phone,\n    up.education_details,\n    up.experience_details,\n    up.skills_details,\n    up.linkedin_profile_url,\n    up.github_profile_url,\n    up.resume_headline,\n    up.current_location\n  FROM user_profiles up\n  WHERE up.id = user_uuid;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
;
