/*\n  # Optimize Remaining RLS Policies - Part 3\n  \n  ## Tables Optimized (Part 3 of 4)\n  - optimized_resumes (3 policies)\n  - auto_apply_applications (4 policies)\n  - user_credentials_vault (4 policies)\n  - auto_apply_sessions (4 policies)\n  - auto_apply_analytics (3 policies)\n  - platform_sessions (4 policies)\n  - authentication_events (2 policies)\n  - automation_state (4 policies)\n  - blog_posts (4 policies)\n  - blog_categories (3 policies)\n  - blog_tags (3 policies)\n  - blog_post_categories (1 policy)\n  - blog_post_tags (1 policy)\n  - webinars (3 policies)\n  - webinar_speakers (3 policies)\n  - webinar_testimonials (3 policies)\n  - webinar_registrations (2 policies)\n  - webinar_updates (3 policies)\n  - webinar_update_views (2 policies)\n  - webinar_email_logs (1 policy)\n*/\n\n-- ============================================================================\n-- OPTIMIZED_RESUMES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own optimized resumes" ON public.optimized_resumes;
\nDROP POLICY IF EXISTS "Users can create own optimized resumes" ON public.optimized_resumes;
\nDROP POLICY IF EXISTS "Users can update own optimized resumes" ON public.optimized_resumes;
\nDROP POLICY IF EXISTS "Users can delete own optimized resumes" ON public.optimized_resumes;
\n\nCREATE POLICY "Users can view own optimized resumes" ON public.optimized_resumes\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own optimized resumes" ON public.optimized_resumes\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own optimized resumes" ON public.optimized_resumes\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own optimized resumes" ON public.optimized_resumes\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- AUTO_APPLY_APPLICATIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own applications" ON public.auto_apply_applications;
\nDROP POLICY IF EXISTS "Users can create own applications" ON public.auto_apply_applications;
\nDROP POLICY IF EXISTS "Users can update own applications" ON public.auto_apply_applications;
\nDROP POLICY IF EXISTS "Users can delete own applications" ON public.auto_apply_applications;
\n\nCREATE POLICY "Users can view own applications" ON public.auto_apply_applications\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own applications" ON public.auto_apply_applications\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own applications" ON public.auto_apply_applications\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own applications" ON public.auto_apply_applications\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- USER_CREDENTIALS_VAULT TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own credentials" ON public.user_credentials_vault;
\nDROP POLICY IF EXISTS "Users can create own credentials" ON public.user_credentials_vault;
\nDROP POLICY IF EXISTS "Users can update own credentials" ON public.user_credentials_vault;
\nDROP POLICY IF EXISTS "Users can delete own credentials" ON public.user_credentials_vault;
\n\nCREATE POLICY "Users can view own credentials" ON public.user_credentials_vault\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own credentials" ON public.user_credentials_vault\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own credentials" ON public.user_credentials_vault\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own credentials" ON public.user_credentials_vault\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- AUTO_APPLY_SESSIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own sessions" ON public.auto_apply_sessions;
\nDROP POLICY IF EXISTS "Users can create own sessions" ON public.auto_apply_sessions;
\nDROP POLICY IF EXISTS "Users can update own sessions" ON public.auto_apply_sessions;
\nDROP POLICY IF EXISTS "Users can delete own sessions" ON public.auto_apply_sessions;
\n\nCREATE POLICY "Users can view own sessions" ON public.auto_apply_sessions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own sessions" ON public.auto_apply_sessions\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own sessions" ON public.auto_apply_sessions\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own sessions" ON public.auto_apply_sessions\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- AUTO_APPLY_ANALYTICS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own analytics" ON public.auto_apply_analytics;
\nDROP POLICY IF EXISTS "Users can create own analytics" ON public.auto_apply_analytics;
\nDROP POLICY IF EXISTS "Users can update own analytics" ON public.auto_apply_analytics;
\n\nCREATE POLICY "Users can view own analytics" ON public.auto_apply_analytics\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can create own analytics" ON public.auto_apply_analytics\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own analytics" ON public.auto_apply_analytics\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- PLATFORM_SESSIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own sessions" ON public.platform_sessions;
\nDROP POLICY IF EXISTS "Users can insert own sessions" ON public.platform_sessions;
\nDROP POLICY IF EXISTS "Users can update own sessions" ON public.platform_sessions;
\nDROP POLICY IF EXISTS "Users can delete own sessions" ON public.platform_sessions;
\n\nCREATE POLICY "Users can view own sessions" ON public.platform_sessions\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own sessions" ON public.platform_sessions\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own sessions" ON public.platform_sessions\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own sessions" ON public.platform_sessions\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- AUTHENTICATION_EVENTS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own authentication events" ON public.authentication_events;
\nDROP POLICY IF EXISTS "Users can insert own authentication events" ON public.authentication_events;
\n\nCREATE POLICY "Users can view own authentication events" ON public.authentication_events\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own authentication events" ON public.authentication_events\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- AUTOMATION_STATE TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can view own automation states" ON public.automation_state;
\nDROP POLICY IF EXISTS "Users can insert own automation states" ON public.automation_state;
\nDROP POLICY IF EXISTS "Users can update own automation states" ON public.automation_state;
\nDROP POLICY IF EXISTS "Users can delete own automation states" ON public.automation_state;
\n\nCREATE POLICY "Users can view own automation states" ON public.automation_state\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own automation states" ON public.automation_state\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can update own automation states" ON public.automation_state\n  FOR UPDATE TO authenticated\n  USING ((SELECT auth.uid()) = user_id)\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can delete own automation states" ON public.automation_state\n  FOR DELETE TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- BLOG_POSTS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Authenticated admins can view all blog posts" ON public.blog_posts;
\nDROP POLICY IF EXISTS "Only admins can insert blog posts" ON public.blog_posts;
\nDROP POLICY IF EXISTS "Only admins can update blog posts" ON public.blog_posts;
\nDROP POLICY IF EXISTS "Only admins can delete blog posts" ON public.blog_posts;
\n\nCREATE POLICY "Authenticated admins can view all blog posts" ON public.blog_posts\n  FOR SELECT TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Only admins can insert blog posts" ON public.blog_posts\n  FOR INSERT TO authenticated\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Only admins can update blog posts" ON public.blog_posts\n  FOR UPDATE TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Only admins can delete blog posts" ON public.blog_posts\n  FOR DELETE TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- BLOG_CATEGORIES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Only admins can insert blog categories" ON public.blog_categories;
\nDROP POLICY IF EXISTS "Only admins can update blog categories" ON public.blog_categories;
\nDROP POLICY IF EXISTS "Only admins can delete blog categories" ON public.blog_categories;
\n\nCREATE POLICY "Only admins can insert blog categories" ON public.blog_categories\n  FOR INSERT TO authenticated\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Only admins can update blog categories" ON public.blog_categories\n  FOR UPDATE TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Only admins can delete blog categories" ON public.blog_categories\n  FOR DELETE TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- BLOG_TAGS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Only admins can insert blog tags" ON public.blog_tags;
\nDROP POLICY IF EXISTS "Only admins can update blog tags" ON public.blog_tags;
\nDROP POLICY IF EXISTS "Only admins can delete blog tags" ON public.blog_tags;
\n\nCREATE POLICY "Only admins can insert blog tags" ON public.blog_tags\n  FOR INSERT TO authenticated\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Only admins can update blog tags" ON public.blog_tags\n  FOR UPDATE TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Only admins can delete blog tags" ON public.blog_tags\n  FOR DELETE TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- BLOG_POST_CATEGORIES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Only admins can manage blog post categories" ON public.blog_post_categories;
\n\nCREATE POLICY "Only admins can manage blog post categories" ON public.blog_post_categories\n  FOR ALL TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- BLOG_POST_TAGS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Only admins can manage blog post tags" ON public.blog_post_tags;
\n\nCREATE POLICY "Only admins can manage blog post tags" ON public.blog_post_tags\n  FOR ALL TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- WEBINARS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Admins can insert webinars" ON public.webinars;
\nDROP POLICY IF EXISTS "Admins can update webinars" ON public.webinars;
\nDROP POLICY IF EXISTS "Admins can delete webinars" ON public.webinars;
\n\nCREATE POLICY "Admins can insert webinars" ON public.webinars\n  FOR INSERT TO authenticated\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can update webinars" ON public.webinars\n  FOR UPDATE TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can delete webinars" ON public.webinars\n  FOR DELETE TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- WEBINAR_SPEAKERS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Admins can insert speakers" ON public.webinar_speakers;
\nDROP POLICY IF EXISTS "Admins can update speakers" ON public.webinar_speakers;
\nDROP POLICY IF EXISTS "Admins can delete speakers" ON public.webinar_speakers;
\n\nCREATE POLICY "Admins can insert speakers" ON public.webinar_speakers\n  FOR INSERT TO authenticated\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can update speakers" ON public.webinar_speakers\n  FOR UPDATE TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can delete speakers" ON public.webinar_speakers\n  FOR DELETE TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- WEBINAR_TESTIMONIALS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Admins can insert testimonials" ON public.webinar_testimonials;
\nDROP POLICY IF EXISTS "Admins can update testimonials" ON public.webinar_testimonials;
\nDROP POLICY IF EXISTS "Admins can delete testimonials" ON public.webinar_testimonials;
\n\nCREATE POLICY "Admins can insert testimonials" ON public.webinar_testimonials\n  FOR INSERT TO authenticated\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can update testimonials" ON public.webinar_testimonials\n  FOR UPDATE TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can delete testimonials" ON public.webinar_testimonials\n  FOR DELETE TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- WEBINAR_REGISTRATIONS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can read own registrations" ON public.webinar_registrations;
\nDROP POLICY IF EXISTS "Users can insert own registrations" ON public.webinar_registrations;
\nDROP POLICY IF EXISTS "Admins and service role can update registrations" ON public.webinar_registrations;
\n\nCREATE POLICY "Users can read own registrations" ON public.webinar_registrations\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own registrations" ON public.webinar_registrations\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Admins and service role can update registrations" ON public.webinar_registrations\n  FOR UPDATE TO authenticated\n  USING (is_admin((SELECT auth.uid())) OR (SELECT auth.uid()) = user_id)\n  WITH CHECK (is_admin((SELECT auth.uid())) OR (SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- WEBINAR_UPDATES TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Admins can insert webinar updates" ON public.webinar_updates;
\nDROP POLICY IF EXISTS "Admins can update webinar updates" ON public.webinar_updates;
\nDROP POLICY IF EXISTS "Admins can delete webinar updates" ON public.webinar_updates;
\n\nCREATE POLICY "Admins can insert webinar updates" ON public.webinar_updates\n  FOR INSERT TO authenticated\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can update webinar updates" ON public.webinar_updates\n  FOR UPDATE TO authenticated\n  USING (is_admin((SELECT auth.uid())))\n  WITH CHECK (is_admin((SELECT auth.uid())));
\n\nCREATE POLICY "Admins can delete webinar updates" ON public.webinar_updates\n  FOR DELETE TO authenticated\n  USING (is_admin((SELECT auth.uid())));
\n\n-- ============================================================================\n-- WEBINAR_UPDATE_VIEWS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can read own update views" ON public.webinar_update_views;
\nDROP POLICY IF EXISTS "Users can insert own update views" ON public.webinar_update_views;
\n\nCREATE POLICY "Users can read own update views" ON public.webinar_update_views\n  FOR SELECT TO authenticated\n  USING ((SELECT auth.uid()) = user_id);
\n\nCREATE POLICY "Users can insert own update views" ON public.webinar_update_views\n  FOR INSERT TO authenticated\n  WITH CHECK ((SELECT auth.uid()) = user_id);
\n\n-- ============================================================================\n-- WEBINAR_EMAIL_LOGS TABLE\n-- ============================================================================\n\nDROP POLICY IF EXISTS "Users can read own email logs" ON public.webinar_email_logs;
\n\nCREATE POLICY "Users can read own email logs" ON public.webinar_email_logs\n  FOR SELECT TO authenticated\n  USING (EXISTS (\n    SELECT 1 FROM public.webinar_registrations\n    WHERE webinar_registrations.id = webinar_email_logs.registration_id\n    AND webinar_registrations.user_id = (SELECT auth.uid())\n  ));
\n;
