/*\n  # Complete Auto-Apply System Schema v2\n\n  ## Changes\n  - Creates all required tables for auto-apply system\n  - Drops existing policies to avoid conflicts\n  - Adds comprehensive RLS policies\n  - Creates storage bucket and policies\n\n  ## Tables Created/Updated\n  1. ai_project_suggestions\n  2. auto_apply_applications  \n  3. user_credentials_vault\n  4. auto_apply_sessions\n  5. auto_apply_field_mappings\n  6. auto_apply_analytics\n*/\n\n-- Drop existing policies on optimized_resumes to avoid conflicts\nDROP POLICY IF EXISTS "Users can view own optimized resumes" ON optimized_resumes;
\nDROP POLICY IF EXISTS "Users can create own optimized resumes" ON optimized_resumes;
\nDROP POLICY IF EXISTS "Users can update own optimized resumes" ON optimized_resumes;
\nDROP POLICY IF EXISTS "Users can delete own optimized resumes" ON optimized_resumes;
\n\n-- Create ai_project_suggestions table\nCREATE TABLE IF NOT EXISTS ai_project_suggestions (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,\n  job_listing_id uuid REFERENCES job_listings(id) ON DELETE CASCADE,\n  resume_id uuid REFERENCES optimized_resumes(id) ON DELETE CASCADE,\n  project_title text NOT NULL,\n  project_summary text NOT NULL,\n  tech_stack text[] DEFAULT ARRAY[]::text[],\n  github_link text,\n  live_demo_link text,\n  code_snippet text,\n  impact_description text,\n  was_selected boolean DEFAULT false,\n  selection_type text CHECK (selection_type IN ('replace', 'add', 'skip')),\n  created_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Create auto_apply_applications table\nCREATE TABLE IF NOT EXISTS auto_apply_applications (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,\n  job_listing_id uuid REFERENCES job_listings(id) ON DELETE CASCADE NOT NULL,\n  resume_version_id uuid REFERENCES optimized_resumes(id) ON DELETE SET NULL,\n  platform text NOT NULL,\n  application_url text NOT NULL,\n  status text DEFAULT 'optimizing' CHECK (status IN ('optimizing', 'filling', 'submitted', 'failed', 'paused')),\n  submission_time timestamptz,\n  error_message text,\n  screenshot_url text,\n  form_data_captured jsonb DEFAULT '{}'::jsonb,\n  paused_at_field text,\n  retry_count integer DEFAULT 0,\n  time_taken_seconds integer,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  updated_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Create user_credentials_vault table\nCREATE TABLE IF NOT EXISTS user_credentials_vault (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,\n  platform text NOT NULL,\n  username text,\n  password_encrypted text,\n  oauth_token text,\n  token_expiry timestamptz,\n  cookies jsonb DEFAULT '{}'::jsonb,\n  is_verified boolean DEFAULT false,\n  last_used timestamptz,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  updated_at timestamptz DEFAULT now() NOT NULL,\n  UNIQUE(user_id, platform)\n);
\n\n-- Create auto_apply_sessions table\nCREATE TABLE IF NOT EXISTS auto_apply_sessions (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,\n  application_id uuid REFERENCES auto_apply_applications(id) ON DELETE CASCADE NOT NULL,\n  current_step text NOT NULL,\n  session_data jsonb DEFAULT '{}'::jsonb,\n  paused_reason text,\n  can_resume boolean DEFAULT true,\n  expires_at timestamptz DEFAULT (now() + interval '24 hours'),\n  created_at timestamptz DEFAULT now() NOT NULL,\n  updated_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Create auto_apply_field_mappings table\nCREATE TABLE IF NOT EXISTS auto_apply_field_mappings (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  platform text NOT NULL,\n  field_label text NOT NULL,\n  field_type text NOT NULL,\n  field_selector text,\n  user_data_mapping text,\n  is_required boolean DEFAULT false,\n  default_value text,\n  usage_count integer DEFAULT 0,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  UNIQUE(platform, field_label)\n);
\n\n-- Create auto_apply_analytics table\nCREATE TABLE IF NOT EXISTS auto_apply_analytics (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,\n  date date DEFAULT CURRENT_DATE NOT NULL,\n  total_applications integer DEFAULT 0,\n  successful_applications integer DEFAULT 0,\n  failed_applications integer DEFAULT 0,\n  average_match_score decimal(5,2),\n  average_time_saved_minutes integer DEFAULT 0,\n  platforms_used jsonb DEFAULT '{}'::jsonb,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  UNIQUE(user_id, date)\n);
\n\n-- Create indexes\nCREATE INDEX IF NOT EXISTS idx_ai_project_suggestions_user_id ON ai_project_suggestions(user_id);
\nCREATE INDEX IF NOT EXISTS idx_ai_project_suggestions_job_listing_id ON ai_project_suggestions(job_listing_id);
\nCREATE INDEX IF NOT EXISTS idx_ai_project_suggestions_resume_id ON ai_project_suggestions(resume_id);
\nCREATE INDEX IF NOT EXISTS idx_auto_apply_applications_user_id ON auto_apply_applications(user_id);
\nCREATE INDEX IF NOT EXISTS idx_auto_apply_applications_job_listing_id ON auto_apply_applications(job_listing_id);
\nCREATE INDEX IF NOT EXISTS idx_auto_apply_applications_status ON auto_apply_applications(status);
\nCREATE INDEX IF NOT EXISTS idx_user_credentials_vault_user_id ON user_credentials_vault(user_id);
\nCREATE INDEX IF NOT EXISTS idx_auto_apply_sessions_user_id ON auto_apply_sessions(user_id);
\nCREATE INDEX IF NOT EXISTS idx_auto_apply_sessions_application_id ON auto_apply_sessions(application_id);
\nCREATE INDEX IF NOT EXISTS idx_auto_apply_analytics_user_id ON auto_apply_analytics(user_id);
\nCREATE INDEX IF NOT EXISTS idx_auto_apply_analytics_date ON auto_apply_analytics(date);
\n\n-- Enable Row Level Security\nALTER TABLE optimized_resumes ENABLE ROW LEVEL SECURITY;
\nALTER TABLE ai_project_suggestions ENABLE ROW LEVEL SECURITY;
\nALTER TABLE auto_apply_applications ENABLE ROW LEVEL SECURITY;
\nALTER TABLE user_credentials_vault ENABLE ROW LEVEL SECURITY;
\nALTER TABLE auto_apply_sessions ENABLE ROW LEVEL SECURITY;
\nALTER TABLE auto_apply_field_mappings ENABLE ROW LEVEL SECURITY;
\nALTER TABLE auto_apply_analytics ENABLE ROW LEVEL SECURITY;
\n\n-- RLS Policies for optimized_resumes\nCREATE POLICY "Users can view own optimized resumes"\n  ON optimized_resumes FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can create own optimized resumes"\n  ON optimized_resumes FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own optimized resumes"\n  ON optimized_resumes FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can delete own optimized resumes"\n  ON optimized_resumes FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\n-- RLS Policies for ai_project_suggestions\nCREATE POLICY "Users can view own project suggestions"\n  ON ai_project_suggestions FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can create own project suggestions"\n  ON ai_project_suggestions FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own project suggestions"\n  ON ai_project_suggestions FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can delete own project suggestions"\n  ON ai_project_suggestions FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\n-- RLS Policies for auto_apply_applications\nCREATE POLICY "Users can view own applications"\n  ON auto_apply_applications FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can create own applications"\n  ON auto_apply_applications FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own applications"\n  ON auto_apply_applications FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can delete own applications"\n  ON auto_apply_applications FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\n-- RLS Policies for user_credentials_vault\nCREATE POLICY "Users can view own credentials"\n  ON user_credentials_vault FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can create own credentials"\n  ON user_credentials_vault FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own credentials"\n  ON user_credentials_vault FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can delete own credentials"\n  ON user_credentials_vault FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\n-- RLS Policies for auto_apply_sessions\nCREATE POLICY "Users can view own sessions"\n  ON auto_apply_sessions FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can create own sessions"\n  ON auto_apply_sessions FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own sessions"\n  ON auto_apply_sessions FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can delete own sessions"\n  ON auto_apply_sessions FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\n-- RLS Policies for auto_apply_field_mappings\nCREATE POLICY "Anyone can view field mappings"\n  ON auto_apply_field_mappings FOR SELECT\n  TO authenticated\n  USING (true);
\n\nCREATE POLICY "System can create field mappings"\n  ON auto_apply_field_mappings FOR INSERT\n  TO authenticated\n  WITH CHECK (true);
\n\nCREATE POLICY "System can update field mappings"\n  ON auto_apply_field_mappings FOR UPDATE\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- RLS Policies for auto_apply_analytics\nCREATE POLICY "Users can view own analytics"\n  ON auto_apply_analytics FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can create own analytics"\n  ON auto_apply_analytics FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own analytics"\n  ON auto_apply_analytics FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\n-- Create or replace updated_at trigger function\nCREATE OR REPLACE FUNCTION update_updated_at_column()\nRETURNS TRIGGER AS $$\nBEGIN\n  NEW.updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql;
\n\n-- Add updated_at triggers\nDROP TRIGGER IF EXISTS update_auto_apply_applications_updated_at ON auto_apply_applications;
\nCREATE TRIGGER update_auto_apply_applications_updated_at\n  BEFORE UPDATE ON auto_apply_applications\n  FOR EACH ROW\n  EXECUTE FUNCTION update_updated_at_column();
\n\nDROP TRIGGER IF EXISTS update_user_credentials_vault_updated_at ON user_credentials_vault;
\nCREATE TRIGGER update_user_credentials_vault_updated_at\n  BEFORE UPDATE ON user_credentials_vault\n  FOR EACH ROW\n  EXECUTE FUNCTION update_updated_at_column();
\n\nDROP TRIGGER IF EXISTS update_auto_apply_sessions_updated_at ON auto_apply_sessions;
\nCREATE TRIGGER update_auto_apply_sessions_updated_at\n  BEFORE UPDATE ON auto_apply_sessions\n  FOR EACH ROW\n  EXECUTE FUNCTION update_updated_at_column();
\n;
