\n\n-- Create subscriptions table\nCREATE TABLE IF NOT EXISTS subscriptions (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE NOT NULL,\n  plan_id text NOT NULL,\n  status text NOT NULL CHECK (status IN ('active', 'expired', 'cancelled')),\n  start_date timestamptz NOT NULL,\n  end_date timestamptz NOT NULL,\n  optimizations_used integer DEFAULT 0 NOT NULL,\n  optimizations_total integer NOT NULL,\n  payment_id text,\n  coupon_used text,\n  created_at timestamptz DEFAULT now() NOT NULL,\n  updated_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Create payment_transactions table\nCREATE TABLE IF NOT EXISTS payment_transactions (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE NOT NULL,\n  subscription_id uuid REFERENCES subscriptions(id) ON DELETE CASCADE,\n  payment_id text NOT NULL,\n  order_id text NOT NULL,\n  amount integer NOT NULL,\n  currency text DEFAULT 'INR' NOT NULL,\n  status text NOT NULL CHECK (status IN ('success', 'failed', 'pending')),\n  coupon_code text,\n  discount_amount integer DEFAULT 0 NOT NULL,\n  final_amount integer NOT NULL,\n  created_at timestamptz DEFAULT now() NOT NULL\n);
\n\n-- Enable Row Level Security\nALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
\nALTER TABLE payment_transactions ENABLE ROW LEVEL SECURITY;
\n\n-- Create policies for subscriptions\nCREATE POLICY "Users can view own subscriptions"\n  ON subscriptions\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "Users can create own subscriptions"\n  ON subscriptions\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\nCREATE POLICY "Users can update own subscriptions"\n  ON subscriptions\n  FOR UPDATE\n  TO authenticated\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());
\n\n-- Create policies for payment_transactions\nCREATE POLICY "Users can view own transactions"\n  ON payment_transactions\n  FOR SELECT\n  TO authenticated\n  USING (user_id = auth.uid());
\n\nCREATE POLICY "Users can create own transactions"\n  ON payment_transactions\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (user_id = auth.uid());
\n\n-- Create function to update subscription timestamp\nCREATE OR REPLACE FUNCTION update_subscription_timestamp()\nRETURNS TRIGGER AS $$\nBEGIN\n  NEW.updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ language 'plpgsql';
\n\n-- Create trigger for subscription timestamp updates\nCREATE TRIGGER update_subscriptions_timestamp\n  BEFORE UPDATE ON subscriptions\n  FOR EACH ROW\n  EXECUTE FUNCTION update_subscription_timestamp();
\n\n-- Create indexes for better performance\nCREATE INDEX IF NOT EXISTS subscriptions_user_id_idx ON subscriptions(user_id);
\nCREATE INDEX IF NOT EXISTS subscriptions_status_idx ON subscriptions(status);
\nCREATE INDEX IF NOT EXISTS subscriptions_end_date_idx ON subscriptions(end_date);
\nCREATE INDEX IF NOT EXISTS payment_transactions_user_id_idx ON payment_transactions(user_id);
\nCREATE INDEX IF NOT EXISTS payment_transactions_payment_id_idx ON payment_transactions(payment_id);
\nCREATE INDEX IF NOT EXISTS payment_transactions_status_idx ON payment_transactions(status);
\n\n-- Function to get active subscription for user\nCREATE OR REPLACE FUNCTION get_active_subscription(user_uuid uuid)\nRETURNS TABLE (\n  subscription_id uuid,\n  plan_id text,\n  optimizations_remaining integer,\n  end_date timestamptz\n) AS $$\nBEGIN\n  RETURN QUERY\n  SELECT \n    s.id,\n    s.plan_id,\n    (s.optimizations_total - s.optimizations_used) as optimizations_remaining,\n    s.end_date\n  FROM subscriptions s\n  WHERE s.user_id = user_uuid\n    AND s.status = 'active'\n    AND s.end_date > now()\n  ORDER BY s.end_date DESC\n  LIMIT 1;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to use optimization (decrement count)\nCREATE OR REPLACE FUNCTION use_optimization(user_uuid uuid)\nRETURNS TABLE (\n  success boolean,\n  remaining integer,\n  message text\n) AS $$\nDECLARE\n  subscription_record subscriptions%ROWTYPE;
\n  remaining_count integer;
\nBEGIN\n  -- Get active subscription\n  SELECT * INTO subscription_record\n  FROM subscriptions\n  WHERE user_id = user_uuid\n    AND status = 'active'\n    AND end_date > now()\n    AND optimizations_used < optimizations_total\n  ORDER BY end_date DESC\n  LIMIT 1;
\n\n  -- Check if subscription exists and has remaining optimizations\n  IF NOT FOUND THEN\n    RETURN QUERY SELECT false, 0, 'No active subscription or optimizations exhausted'::text;
\n    RETURN;
\n  END IF;
\n\n  -- Update optimization count\n  UPDATE subscriptions\n  SET optimizations_used = optimizations_used + 1,\n      updated_at = now()\n  WHERE id = subscription_record.id;
\n\n  -- Calculate remaining optimizations\n  remaining_count := subscription_record.optimizations_total - subscription_record.optimizations_used - 1;
\n\n  RETURN QUERY SELECT true, remaining_count, 'Optimization used successfully'::text;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
;
