/*\n  # Add Session Booking System\n\n  1. New Tables\n    - `session_services`\n      - `id` (uuid, primary key) - unique service identifier\n      - `title` (text) - service display name\n      - `description` (text) - detailed description\n      - `price` (integer) - price in paise (99900 = Rs 999)\n      - `currency` (text) - currency code, default INR\n      - `highlights` (jsonb) - array of bullet-point highlights\n      - `bonus_credits` (integer) - JD credits awarded on booking\n      - `max_slots_per_day` (integer) - max bookings per day (default 5)\n      - `time_slots` (jsonb) - array of available time slot strings\n      - `is_active` (boolean) - whether service is bookable\n      - `created_at`, `updated_at` (timestamptz)\n\n    - `session_slots`\n      - `id` (uuid, primary key)\n      - `service_id` (uuid FK -> session_services)\n      - `slot_date` (date) - the date of the slot\n      - `time_slot` (text) - e.g. "10:00-11:00"\n      - `status` (text) - available / booked / blocked\n      - `booked_by` (uuid FK -> auth.users, nullable)\n      - `booking_id` (uuid FK -> session_bookings, nullable)\n      - `created_at`, `updated_at` (timestamptz)\n      - UNIQUE constraint on (service_id, slot_date, time_slot)\n\n    - `session_bookings`\n      - `id` (uuid, primary key)\n      - `user_id` (uuid FK -> auth.users)\n      - `service_id` (uuid FK -> session_services)\n      - `slot_id` (uuid FK -> session_slots)\n      - `booking_date` (date) - the booked date\n      - `time_slot` (text) - the booked time slot\n      - `payment_transaction_id` (uuid FK -> payment_transactions, nullable)\n      - `status` (text) - confirmed / cancelled / completed / no_show\n      - `bonus_credits_awarded` (integer) - credits given\n      - `booking_code` (text, unique) - human-readable booking ID\n      - `user_name` (text) - name at time of booking\n      - `user_email` (text) - email at time of booking\n      - `user_phone` (text, nullable) - phone at time of booking\n      - `cancellation_reason` (text, nullable)\n      - `created_at`, `updated_at` (timestamptz)\n\n  2. Functions\n    - `book_slot_atomically` - atomic slot booking with race condition protection\n    - `generate_booking_code` - generates human-readable booking codes\n\n  3. Security\n    - RLS enabled on all 3 tables\n    - Users can read active services\n    - Users can read available slots\n    - Users can read/manage their own bookings\n    - Admins can read/write all data\n\n  4. Seed Data\n    - Initial "Resume Session - Career Transformation" service at Rs 999\n*/\n\n-- 1. Create session_services table\nCREATE TABLE IF NOT EXISTS session_services (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  title text NOT NULL,\n  description text NOT NULL DEFAULT '',\n  price integer NOT NULL,\n  currency text NOT NULL DEFAULT 'INR',\n  highlights jsonb NOT NULL DEFAULT '[]'::jsonb,\n  bonus_credits integer NOT NULL DEFAULT 0,\n  max_slots_per_day integer NOT NULL DEFAULT 5,\n  time_slots jsonb NOT NULL DEFAULT '[]'::jsonb,\n  is_active boolean NOT NULL DEFAULT true,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  updated_at timestamptz NOT NULL DEFAULT now()\n);
\n\nALTER TABLE session_services ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Anyone can view active services"\n  ON session_services FOR SELECT\n  TO authenticated\n  USING (is_active = true);
\n\nCREATE POLICY "Admins can manage services"\n  ON session_services FOR ALL\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM profiles\n      WHERE profiles.id = auth.uid()\n      AND profiles.is_admin = true\n    )\n  );
\n\n-- 2. Create session_bookings table (before session_slots so FK works)\nCREATE TABLE IF NOT EXISTS session_bookings (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid NOT NULL REFERENCES auth.users(id),\n  service_id uuid NOT NULL,\n  slot_id uuid,\n  booking_date date NOT NULL,\n  time_slot text NOT NULL,\n  payment_transaction_id uuid REFERENCES payment_transactions(id),\n  status text NOT NULL DEFAULT 'confirmed',\n  bonus_credits_awarded integer NOT NULL DEFAULT 0,\n  booking_code text UNIQUE NOT NULL,\n  user_name text NOT NULL DEFAULT '',\n  user_email text NOT NULL DEFAULT '',\n  user_phone text,\n  cancellation_reason text,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  CONSTRAINT valid_booking_status CHECK (status IN ('confirmed', 'cancelled', 'completed', 'no_show'))\n);
\n\nALTER TABLE session_bookings ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Users can view own bookings"\n  ON session_bookings FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can insert own bookings"\n  ON session_bookings FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own bookings"\n  ON session_bookings FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Admins can view all bookings"\n  ON session_bookings FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM profiles\n      WHERE profiles.id = auth.uid()\n      AND profiles.is_admin = true\n    )\n  );
\n\nCREATE POLICY "Admins can update all bookings"\n  ON session_bookings FOR UPDATE\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM profiles\n      WHERE profiles.id = auth.uid()\n      AND profiles.is_admin = true\n    )\n  )\n  WITH CHECK (\n    EXISTS (\n      SELECT 1 FROM profiles\n      WHERE profiles.id = auth.uid()\n      AND profiles.is_admin = true\n    )\n  );
\n\n-- 3. Create session_slots table\nCREATE TABLE IF NOT EXISTS session_slots (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  service_id uuid NOT NULL REFERENCES session_services(id),\n  slot_date date NOT NULL,\n  time_slot text NOT NULL,\n  status text NOT NULL DEFAULT 'available',\n  booked_by uuid REFERENCES auth.users(id),\n  booking_id uuid REFERENCES session_bookings(id),\n  created_at timestamptz NOT NULL DEFAULT now(),\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  CONSTRAINT unique_service_date_slot UNIQUE (service_id, slot_date, time_slot),\n  CONSTRAINT valid_slot_status CHECK (status IN ('available', 'booked', 'blocked'))\n);
\n\nALTER TABLE session_slots ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Anyone can view slots"\n  ON session_slots FOR SELECT\n  TO authenticated\n  USING (true);
\n\nCREATE POLICY "Admins can manage slots"\n  ON session_slots FOR ALL\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM profiles\n      WHERE profiles.id = auth.uid()\n      AND profiles.is_admin = true\n    )\n  );
\n\nCREATE POLICY "System can update slots on booking"\n  ON session_slots FOR UPDATE\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\nCREATE POLICY "System can insert slots"\n  ON session_slots FOR INSERT\n  TO authenticated\n  WITH CHECK (true);
\n\n-- Add FK from session_bookings to session_services and session_slots\nALTER TABLE session_bookings\n  ADD CONSTRAINT fk_session_bookings_service\n  FOREIGN KEY (service_id) REFERENCES session_services(id);
\n\nALTER TABLE session_bookings\n  ADD CONSTRAINT fk_session_bookings_slot\n  FOREIGN KEY (slot_id) REFERENCES session_slots(id);
\n\n-- 4. Create indexes\nCREATE INDEX IF NOT EXISTS idx_session_slots_date ON session_slots(slot_date);
\nCREATE INDEX IF NOT EXISTS idx_session_slots_service_date ON session_slots(service_id, slot_date);
\nCREATE INDEX IF NOT EXISTS idx_session_bookings_user ON session_bookings(user_id);
\nCREATE INDEX IF NOT EXISTS idx_session_bookings_date ON session_bookings(booking_date);
\nCREATE INDEX IF NOT EXISTS idx_session_bookings_status ON session_bookings(status);
\n\n-- 5. Function to generate booking codes like PB-20250206-001\nCREATE OR REPLACE FUNCTION generate_booking_code(booking_date date)\nRETURNS text\nLANGUAGE plpgsql\nAS $$\nDECLARE\n  date_str text;
\n  seq_num integer;
\n  code text;
\nBEGIN\n  date_str := to_char(booking_date, 'YYYYMMDD');
\n  \n  SELECT COALESCE(MAX(\n    CAST(SUBSTRING(booking_code FROM '[0-9]+$') AS integer)\n  ), 0) + 1\n  INTO seq_num\n  FROM session_bookings\n  WHERE session_bookings.booking_date = generate_booking_code.booking_date;
\n  \n  code := 'PB-' || date_str || '-' || LPAD(seq_num::text, 3, '0');
\n  RETURN code;
\nEND;
\n$$;
\n\n-- 6. Atomic booking function\nCREATE OR REPLACE FUNCTION book_slot_atomically(\n  p_user_id uuid,\n  p_service_id uuid,\n  p_slot_date date,\n  p_time_slot text,\n  p_payment_transaction_id uuid DEFAULT NULL,\n  p_user_name text DEFAULT '',\n  p_user_email text DEFAULT '',\n  p_user_phone text DEFAULT NULL\n)\nRETURNS jsonb\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  v_slot_id uuid;
\n  v_booking_id uuid;
\n  v_booking_code text;
\n  v_bonus_credits integer;
\n  v_addon_type_id uuid;
\n  v_slot_count integer;
\n  v_max_slots integer;
\nBEGIN\n  -- Get service info\n  SELECT bonus_credits, max_slots_per_day\n  INTO v_bonus_credits, v_max_slots\n  FROM session_services\n  WHERE id = p_service_id AND is_active = true;
\n\n  IF NOT FOUND THEN\n    RETURN jsonb_build_object('success', false, 'error', 'Service not found or inactive');
\n  END IF;
\n\n  -- Check how many slots are already booked for this date\n  SELECT COUNT(*)\n  INTO v_slot_count\n  FROM session_slots\n  WHERE service_id = p_service_id\n    AND slot_date = p_slot_date\n    AND status = 'booked';
\n\n  IF v_slot_count >= v_max_slots THEN\n    RETURN jsonb_build_object('success', false, 'error', 'All slots for this date are fully booked');
\n  END IF;
\n\n  -- Try to find existing slot row\n  SELECT id INTO v_slot_id\n  FROM session_slots\n  WHERE service_id = p_service_id\n    AND slot_date = p_slot_date\n    AND time_slot = p_time_slot\n  FOR UPDATE;
\n\n  IF FOUND THEN\n    -- Check if already booked or blocked\n    IF (SELECT status FROM session_slots WHERE id = v_slot_id) != 'available' THEN\n      RETURN jsonb_build_object('success', false, 'error', 'This slot is no longer available. Please pick another slot.');
\n    END IF;
\n  ELSE\n    -- Create the slot row\n    INSERT INTO session_slots (service_id, slot_date, time_slot, status)\n    VALUES (p_service_id, p_slot_date, p_time_slot, 'available')\n    RETURNING id INTO v_slot_id;
\n  END IF;
\n\n  -- Generate booking code\n  v_booking_code := generate_booking_code(p_slot_date);
\n\n  -- Create the booking\n  INSERT INTO session_bookings (\n    user_id, service_id, slot_id, booking_date, time_slot,\n    payment_transaction_id, status, bonus_credits_awarded,\n    booking_code, user_name, user_email, user_phone\n  )\n  VALUES (\n    p_user_id, p_service_id, v_slot_id, p_slot_date, p_time_slot,\n    p_payment_transaction_id, 'confirmed', v_bonus_credits,\n    v_booking_code, p_user_name, p_user_email, p_user_phone\n  )\n  RETURNING id INTO v_booking_id;
\n\n  -- Mark slot as booked\n  UPDATE session_slots\n  SET status = 'booked',\n      booked_by = p_user_id,\n      booking_id = v_booking_id,\n      updated_at = now()\n  WHERE id = v_slot_id;
\n\n  -- Award bonus JD credits\n  IF v_bonus_credits > 0 THEN\n    SELECT id INTO v_addon_type_id\n    FROM addon_types\n    WHERE type_key = 'optimization'\n    LIMIT 1;
\n\n    IF v_addon_type_id IS NOT NULL THEN\n      INSERT INTO user_addon_credits (\n        user_id, addon_type_id, quantity_purchased, quantity_remaining,\n        payment_transaction_id\n      )\n      VALUES (\n        p_user_id, v_addon_type_id, v_bonus_credits, v_bonus_credits,\n        p_payment_transaction_id\n      );
\n    END IF;
\n  END IF;
\n\n  RETURN jsonb_build_object(\n    'success', true,\n    'booking_id', v_booking_id,\n    'booking_code', v_booking_code,\n    'slot_id', v_slot_id,\n    'bonus_credits', v_bonus_credits\n  );
\nEND;
\n$$;
\n\n-- 7. Seed initial service\nINSERT INTO session_services (title, description, price, currency, highlights, bonus_credits, max_slots_per_day, time_slots, is_active)\nVALUES (\n  'Resume Session - Career Transformation',\n  'Get your resume reviewed by an ATS expert in a 1-on-1 live session. Learn how ATS shortlisting works, get practical guidance to improve your resume, and receive bonus JD optimization credits.',\n  99900,\n  'INR',\n  '["ATS Resume Review by Expert", "Learn ATS shortlisting logic", "Practical guidance on resume improvement", "Bonus: 10 JD Optimization Credits"]'::jsonb,\n  10,\n  5,\n  '["10:00-11:00", "11:00-12:00", "12:00-13:00", "14:00-15:00", "15:00-16:00"]'::jsonb,\n  true\n)\nON CONFLICT DO NOTHING;
;
