/*\n  # Create Referral Purchases Table\n\n  1. New Table\n    - `referral_purchases` - Tracks user purchases of referral access\n      - `id` (uuid, primary key)\n      - `user_id` (uuid, FK to user_profiles)\n      - `referral_listing_id` (uuid, FK to referral_listings)\n      - `purchase_type` (text) - 'query' or 'profile'\n      - `amount_paid` (integer, paise)\n      - `payment_id` (text, nullable)\n      - `order_id` (text, nullable)\n      - `status` (text) - 'pending', 'success', 'failed'\n\n  2. Security\n    - RLS enabled\n    - Users can view/insert/update their own purchases\n    - Admins can view all purchases\n*/\n\nCREATE TABLE IF NOT EXISTS referral_purchases (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid NOT NULL REFERENCES user_profiles(id),\n  referral_listing_id uuid NOT NULL REFERENCES referral_listings(id),\n  purchase_type text NOT NULL CHECK (purchase_type IN ('query', 'profile')),\n  amount_paid integer NOT NULL DEFAULT 0,\n  payment_id text,\n  order_id text,\n  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'success', 'failed')),\n  created_at timestamptz NOT NULL DEFAULT now()\n);
\n\nALTER TABLE referral_purchases ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Users can view own referral purchases"\n  ON referral_purchases FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can insert own referral purchases"\n  ON referral_purchases FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own referral purchases"\n  ON referral_purchases FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Admins can view all referral purchases"\n  ON referral_purchases FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM auth.users\n      WHERE auth.users.id = auth.uid()\n      AND (\n        auth.users.raw_app_meta_data->>'role' = 'admin'\n        OR auth.users.email = 'primoboostai@gmail.com'\n      )\n    )\n  );
\n\nCREATE INDEX IF NOT EXISTS idx_referral_purchases_user ON referral_purchases(user_id);
\nCREATE INDEX IF NOT EXISTS idx_referral_purchases_listing ON referral_purchases(referral_listing_id);
\n;
