/*\n  # Fix mutable search_path security vulnerability on all public functions\n\n  1. Security Fixes\n    - Set `search_path = public, pg_temp` on 25 functions missing this setting\n    - Prevents search_path hijacking attacks\n    - Critical fix for SECURITY DEFINER function `book_slot_atomically`\n\n  2. Functions Fixed\n    - All trigger functions (update_*_updated_at, etc.)\n    - Business logic functions (book_slot_atomically, generate_booking_code, etc.)\n    - Utility functions (calculate_bubble_score, extract_skills_from_text, etc.)\n\n  3. Important Notes\n    - Only modifies the search_path config, no logic changes\n*/\n\nALTER FUNCTION public.book_slot_atomically(uuid, uuid, date, text, uuid, text, text, text)\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.assign_referral_code(uuid)\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.calculate_bubble_score(numeric, integer, boolean, text)\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.calculate_commission_percentage()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.ensure_single_primary_resume()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.extract_skills_from_text(text)\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.generate_booking_code(date)\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.generate_device_fingerprint(text, text, text, text)\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.trg_touch_updated_at()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_app_metrics_updated_at()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_blog_post_updated_at()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_device_timestamp()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_job_fetch_configs_updated_at()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_job_listings_timestamp()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_job_updates_updated_at()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_linkedin_profile_optimizations_updated_at()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_portfolio_updated_at()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_profile_timestamp()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_recommendation_timestamp()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_smart_updated_at_column()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_subscription_timestamp()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_survey_subscription_timestamp()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_updated_at_column()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_wallet_updated_at()\n  SET search_path = public, pg_temp;
\n\nALTER FUNCTION public.update_webinar_updates_timestamp()\n  SET search_path = public, pg_temp;
\n;
