/*\n  # Add scoring columns to optimization_sessions\n\n  1. Modified Tables\n    - `optimization_sessions`\n      - Added `before_score` (integer) - overall score before optimization\n      - Added `after_score` (integer) - overall score after optimization\n      - Added `before_parameters` (jsonb) - 20-parameter scores before\n      - Added `after_parameters` (jsonb) - 20-parameter scores after\n      - Added `category_deltas` (jsonb) - category-level before/after deltas\n      - Added `gap_classification` (jsonb) - fixable vs non-fixable gap data\n      - Added `optimized_resume` (jsonb) - final optimized resume JSON\n      - Added `changes_applied` (jsonb) - list of changes made\n      - Added `iterations_count` (integer) - optimization loop count\n      - Added `reached_target` (boolean) - whether 90+ was achieved\n      - Added `processing_time_ms` (integer) - total processing time\n      - Added `parsing_method` (text) - direct_text or ocr\n\n  2. Security\n    - No changes needed, RLS already enabled\n*/\n\nDO $$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'before_score') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN before_score integer NOT NULL DEFAULT 0;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'after_score') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN after_score integer NOT NULL DEFAULT 0;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'before_parameters') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN before_parameters jsonb NOT NULL DEFAULT '[]'::jsonb;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'after_parameters') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN after_parameters jsonb NOT NULL DEFAULT '[]'::jsonb;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'category_deltas') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN category_deltas jsonb NOT NULL DEFAULT '[]'::jsonb;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'gap_classification') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN gap_classification jsonb NOT NULL DEFAULT '{}'::jsonb;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'optimized_resume') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN optimized_resume jsonb NOT NULL DEFAULT '{}'::jsonb;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'changes_applied') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN changes_applied jsonb NOT NULL DEFAULT '[]'::jsonb;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'iterations_count') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN iterations_count integer NOT NULL DEFAULT 0;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'reached_target') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN reached_target boolean NOT NULL DEFAULT false;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'processing_time_ms') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN processing_time_ms integer NOT NULL DEFAULT 0;
\n  END IF;
\n  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'optimization_sessions' AND column_name = 'parsing_method') THEN\n    ALTER TABLE optimization_sessions ADD COLUMN parsing_method text NOT NULL DEFAULT 'direct_text';
\n  END IF;
\nEND $$;
\n;
