/*\n  # Fix Referral RLS Policies to use is_admin() function\n\n  Replaces all admin checks on referral tables to use the existing\n  `is_admin(uuid)` function that checks user_profiles.role instead of\n  auth.users.raw_app_meta_data which doesn't contain the role field.\n*/\n\n-- Drop existing policies on referral_listings\nDROP POLICY IF EXISTS "Admins can view all referral listings" ON referral_listings;
\nDROP POLICY IF EXISTS "Admins can insert referral listings" ON referral_listings;
\nDROP POLICY IF EXISTS "Admins can update referral listings" ON referral_listings;
\nDROP POLICY IF EXISTS "Admins can delete referral listings" ON referral_listings;
\n\n-- Recreate with is_admin()\nCREATE POLICY "Admins can view all referral listings"\n  ON referral_listings FOR SELECT\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can insert referral listings"\n  ON referral_listings FOR INSERT\n  TO authenticated\n  WITH CHECK (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can update referral listings"\n  ON referral_listings FOR UPDATE\n  TO authenticated\n  USING (is_admin(auth.uid()))\n  WITH CHECK (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can delete referral listings"\n  ON referral_listings FOR DELETE\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\n-- Drop existing policies on referral_pricing\nDROP POLICY IF EXISTS "Admins can update referral pricing" ON referral_pricing;
\n\nCREATE POLICY "Admins can update referral pricing"\n  ON referral_pricing FOR UPDATE\n  TO authenticated\n  USING (is_admin(auth.uid()))\n  WITH CHECK (is_admin(auth.uid()));
\n\n-- Drop existing policies on referral_purchases\nDROP POLICY IF EXISTS "Admins can view all referral purchases" ON referral_purchases;
\n\nCREATE POLICY "Admins can view all referral purchases"\n  ON referral_purchases FOR SELECT\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n\n-- Drop existing admin policies on referral_consultation_slots\nDROP POLICY IF EXISTS "Admins can insert consultation slots" ON referral_consultation_slots;
\nDROP POLICY IF EXISTS "Admins can update consultation slots" ON referral_consultation_slots;
\nDROP POLICY IF EXISTS "Admins can delete consultation slots" ON referral_consultation_slots;
\n\nCREATE POLICY "Admins can insert consultation slots"\n  ON referral_consultation_slots FOR INSERT\n  TO authenticated\n  WITH CHECK (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can update consultation slots"\n  ON referral_consultation_slots FOR UPDATE\n  TO authenticated\n  USING (is_admin(auth.uid()))\n  WITH CHECK (is_admin(auth.uid()));
\n\nCREATE POLICY "Admins can delete consultation slots"\n  ON referral_consultation_slots FOR DELETE\n  TO authenticated\n  USING (is_admin(auth.uid()));
\n;
